### ISSUE TITLE
Clean install Windows 10 ISO (Updated June) is now requesting having to connect to the internet and login with a MS account during installation (even without being connected at all)

### ISSUE THREAD

**Issue by MELERIX** [pbatard/rufus#2514] opened 2024-07-01 21:00 UTC
so I guess now it time to add the same option of Windows 11 bypassnro but for Windows 10 too.

**Comment by pbatard** [comment] 2024-07-01 21:55
Is that ISO available without an MSDN account?

I'm afraid that, unless an ISO is made available to everybody by Microsoft, it's hard to justify adding a workaround for it, and my understanding is that 22H2 is the last publicly available release of Windows 10...

**Comment by thecatontheceiling** [comment] 2024-07-01 22:07
You linked to a piracy website.

That's not "made publicly available by Microsoft".

**Comment by pbatard** [comment] 2024-07-01 22:20
Yes, I'm afraid anybody can take an ISO from MSDN, or a dynamically built ISO, and put it online through one mean or another, but that does not qualify as _"made available to everybody by Microsoft"_ from something like https://www.microsoft.com/en-us/software-download/windows10 (which still lists 22H2 as the most up to date release that Microsoft does make available for non MSDN users).

So, unless/until Microsoft themselves do make Windows 10 2024.06 update available to everybody without a subscription, I'm going to consider adding workarounds for editions of Windows that only MSDN paid subscribers can **officially** get access to is going to restrict the landscape of users enough to limit how much of a priority this should be.

**Comment by wallrik** [comment] 2024-07-01 23:13
I was curious to see this, but I can't reproduce this with an updated ISO.

ISO: `en-us_windows_10_consumer_editions_version_22h2_updated_june_2024_x64_dvd_a8751094.iso`
Build: `10.0.19045.4529`

Looks like any other Windows 10 setup. 🤷‍♂️ What does the screen look like @MELERIX?

**Comment by thecatontheceiling** [comment] 2024-07-02 00:18
Oh yeah I forgot to mention.
Edition matters. Home edition will try to force things like a Microsoft account much more aggressively than other editions, simply because it's the cheapest edition and the lowest tier.

**Comment by wallrik** [comment] 2024-07-02 00:39
> I guess maybe ot depend of the Edition selected, for example I've tested with Home and Home SL.

Oh yeah, I tried to reproduce on Pro. I am able to reproduce on Home.

![NRO](https://github.com/pbatard/rufus/assets/10890923/a523fd21-03ab-4df1-908a-e5d07af492ab)

And `BypassNRO` seem to work for Windows 10 as well, like you said. 👍

**Comment by pbatard** [comment] 2024-07-02 10:00
Okay, so it's really "same old" with something that I didn't really plan to address in Rufus anyway since Windows 10 is nearing EOL and there are too many Microsoft shenanigans keeping me busy with Windows 11.

As such, I will close this issue.

**Closed by pbatard** 2024-07-02 10:00 UTC
