### ISSUE TITLE
Super GRUB Disk Software

### ISSUE THREAD

**Issue by Oddbrother** [pbatard/rufus#567] opened 2015-08-06 01:45 UTC
Software developed by Super GRUB Disk, such as [Super Grub2 Disk](http://www.supergrubdisk.org/super-grub2-disk/) and [Rescatux](http://www.supergrubdisk.org/rescatux/), use a universally friendly disk image that can be written to either CD, floppy disk, or a USB storage device.

When using this in Rufus, though, you are restricted to BIOS booting... whereas when writing it on CD or floppy, you have the option to boot it through either BIOS or UEFI.

I want to have the latter support for my MacBook Pro while still using the disc drive for other things, but I can't considering this limitation.

If you can, please help me find a way to write Super Grub2 Disk on USB and making it EFI bootable on my Mac system.

There's an [All-in-one hybrid ISO](https://forja.cenatic.es/frs/download.php/file/1844/super_grub2_disk_hybrid_2.02s3.iso) which is a rocky situation, but works with Rufus for MBR only (which is probably just i386-pc).
A [standalone EFI file](https://forja.cenatic.es/frs/download.php/file/1856/super_grub2_disk_standalone_x86_64_efi_2.02s3.EFI), which requires advanced knowledge to set up... and there isn't a guide anywhere specifically for this file, so blind improvisation. Besides, it doesn't work with Rufus anyway.
An [i386-pc ISO](https://forja.cenatic.es/frs/download.php/file/1846/super_grub2_disk_i386_pc_2.02s3.iso), which works with Rufus for MBR only.
An [x86_64-efi ISO](https://forja.cenatic.es/frs/download.php/file/1848/super_grub2_disk_x86_64_efi_2.02s3.iso), which doesn't work with Rufus at all. It's supposed to be EFI bootable as it says, but...

**Comment by pbatard** [comment] 2015-08-06 08:32
The problem is those guys didn't follow the UEFI specifications and placed a `/EFI/boot/bootx64.efi`. There's no special knowledge to have for their users if the people creating these images had focused on __following the official UEFI specs__ instead of drinking the ISOHybrid kool-aid, which, as many seem to fail to understand, only helps maintainers, NOT their users.

Now, Rufus can write ISOHybrid images. Just use the [<kbd>Alt</kbd>-<kbd>I</kbd> cheat mode](https://github.com/pbatard/rufus/wiki/FAQ#Power_keysCheat_modes).

Again, what you have demonstrated here is that ISOHybrid images are more of an inconvenience than anything for __users__. The sooner people creating ISOs realize that, the better.

Since there's not much I can do in Rufus (I can't craft an UEFI boot loaded out of thin air for an ISO - it needs to be specifically tailored for each system), I will close this issue. You should contact the makers of these ISOs if you want to solve your problem.

**Closed by pbatard** 2015-08-06 08:32 UTC
