### ISSUE TITLE
Add Etcher to benchmark table

### ISSUE THREAD

**Issue by sschuberth** [pbatard/rufus#1437] opened 2020-01-21 16:59 UTC
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Could we please also get numbers for [Etcher](https://www.balena.io/etcher/) added to [the benchmark table in the README](https://github.com/pbatard/rufus#enhancementsbugs)? That would be interesting, even if / exactly because [Etcher writes only images in DD mode](https://github.com/pbatard/rufus/issues/1262#issuecomment-453824064).

And maybe create a separate "Benchmarks" section in the README while at it? It reads odd to find the benchmarks under "Enhancements/Bugs".

**Comment by pbatard** [comment] 2020-01-21 17:14
Duplicate of #1153.

I am of course planning to have Etcher in the updated benchmarks. As you can imagine however, updating the benchmark is obviously not very high priority on my list when there are bugs to fix and other improvements that take precedence. But I will get to it, _eventually_...

**Closed by pbatard** 2020-01-21 17:14 UTC
