### ISSUE TITLE
Command line 

### ISSUE THREAD

**Issue by couchcommander** [pbatard/rufus#725] opened 2016-03-28 20:06 UTC
Is there a way to control Rufus or will there be soon a way to control Rufus by command line? I am try to build a lot USBs that  need to be UEFI-NTFS. Your software work great at creating them, but i would like to script this function into a auto UEFI-NTFS USB-Maker application. I have created one right now, but i have to use the oshell.sendkeys command in VBS to do it and if some clicks on the screen or a pop happen it mess up my script. Let me know if you need any more information, thank you.

**Comment by pbatard** [comment] 2016-03-28 20:09
Duplicate of #111. Please perform a search next time. Don't expect anything fast on #111 however (mostly because of [this](https://github.com/pbatard/rufus/wiki/FAQ#Why_isnt_Rufus_development_faster)) as well as the fact that, unfortunately, few people seem to have much use for command line in Rufus, and therefore it is being prioritized accordingly compared to features that will benefit a lot more people.

**Closed by pbatard** 2016-03-28 20:09 UTC
