### ISSUE TITLE
Rufus 2.13.1081 Error:  Could not open media. It may be in use by another process. 

### ISSUE THREAD

**Issue by Krammig** [pbatard/rufus#930] opened 2017-04-10 10:03 UTC
Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.
- [x] I clicked the `Log` button in Rufus and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking the "bad blocks" check box in Rufus, and confirmed that my USB is not defective
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive
  - [x] Plugging the USB into a different port
  - [ ] Running Rufus on a different computer
- [x] If using an ISO image, I clicked on the `#` button (at the bottom of the Rufus interface), to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Error:  Could not open media. It may be in use by another process. 

I have tried several setting changes however every time it stalls out at the same point,  Writing Master Boot Record. Log says waiting for access. Then it fails. 

cheers

Log
---
```
Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'H:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Rufus Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 63 sectors
Deleting partitions...
Partitioning (MBR)...
Adding extra partition
Reserved 1 tracks (31.5 KB) for extra partition
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Set bootable USB partition as 0x80
Using Rufus MBR
Found volume GUID \\?\Volume{a07d8418-050c-11e7-9820-9cb70d689ce9}\
Waiting for access...
Could not open drive \\?\Volume{a07d8418-050c-11e7-9820-9cb70d689ce9}: [0x00000020] The process cannot access the file because it is being used by another process.
Could not re-mount volume for partition boot record access
\\?\Volume{a07d8418-050c-11e7-9820-9cb70d689ce9}\ was already mounted as H:\
Re-mounted volume as 'H:' after error

Found USB 3.0 device 'SanDisk Ultra USB 3.0 USB Device' (0781:5591)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 7551, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x009D07B0
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 57.8 GB (62109186048 bytes)
  Start Sector: 63, Boot: Yes
Partition 2:
  Type: Rufus Extra (0xea)
  Size: 31.5 KB (32256 bytes)
  Start Sector: 121307067, Boot: No
```

**Comment by pbatard** [comment] 2017-04-10 10:05
> - [x] I performed a search in the issue tracker for similar issues, using keywords relevant to my problem.

No you didn't, because this is a duplicate of #924.

**Closed by pbatard** 2017-04-10 10:05 UTC
