### ISSUE TITLE
Access denied(rufus 2.4)

### ISSUE THREAD

**Issue by cmiuc** [pbatard/rufus#623] opened 2015-10-18 13:08 UTC
Seen many had issues without real info... other than mistakes.

I tried it on 2 computers(windows 10 x32 and x64)  same issue.  using windows defender and windows firewall...so not big issue with 3rd party.

works sometimes and most times not... only way to get around it is to start the computer in safemode and run rufus and create my UEFI usb.  So something in windows is blocking access to the physical drive

my log in part
Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Could not get exclusive access to device \\.\PHYSICALDRIVE1: [0x00000005] Access is denied.

Found USB 2.0 device 'Kingston DataTraveler 2.0 USB Device' (0930:6544)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 942, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00358981
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 7.2 GB (7755038720 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes

if any clues, please let me know. thanks!

**Comment by pbatard** [comment] 2015-10-18 13:44
Duplicate of #605. This is a pure Microsoft issue with the Windows insider builds.

**Closed by pbatard** 2015-10-18 13:44 UTC
