### ISSUE TITLE
Rufus does not detect and thus will not write grub bios boot loaders

### ISSUE THREAD

**Issue by Thinstation** [pbatard/rufus#2508] opened 2024-06-15 13:40 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Rufus does not detect grub bios mode boot loader. Once upon a time, I used syslinux for bios mode, but that project is not going anywhere. To simplify my own project, I have dropped all bootloaders besides grub. I distribute all the necessary files to create a bootable usb drive with the ISO. I have long recommended Rufus and given credit to Pete Batard for it's creation. Maybe this is partially a feature request. Anyways.....

When Rufus loads my ISO, no option is given to write a BIOS/UEFI target like 
![image](https://github.com/pbatard/rufus/assets/2846334/364f7b4c-ff50-4c8d-bc22-cea73c8f3bde)
Instead, the user only sees 
![image](https://github.com/pbatard/rufus/assets/2846334/d696e938-6b78-4ca5-aecf-d8fd0aa0899b)
I do provide the necessary files to make the drive bootable in BIOS mode. 
<img width="536" alt="image" src="https://github.com/pbatard/rufus/assets/2846334/00528639-5fb9-4719-b50a-8a7d99df5a4e">
boot.img is the grub boot sector and core.img is grub bios binary
Because of the way that grub works, there may not be a standard for naming of the grub binary, but maybe we can establish one?

In linux, I would run the following, and I have a utility to do it, but users love windows so.....

        dd if=$overlay/boot/grub/boot.img of=$device bs=446 count=1
        dd if=$overlay/boot/grub/core.img of=$device bs=512 seek=1

Log
---
```
Rufus x64 v4.5.2180 (Portable)
Windows version: Windows 11 Pro x64 (Build 22631.3737)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.12
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 2.0 device 'USB DISK 3.0 USB Device' (13FE:6300)
NOTE: This device is a USB 3.0 device operating at lower speed...
1 device found
Disk type: Removable, Disk size: 32 GB, Sector size: 512 bytes
Cylinders: 3769, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 3
Disk ID: 0x90909090
Drive has an unknown Master Boot Record
Partition 1:
  Type: EFI System Partition (0xef)
  Detected File System: FAT32
  Size: 32.5 MB (34091008 bytes)
  Start Sector: 1, Boot: No
Partition 2:
  Type: FreeBSD (0xa5)
  Detected File System: (Unrecognized)
  Size: 978.3 MB (1025810432 bytes)
  Start Sector: 66585, Boot: Yes
Partition 3:
  Type: FAT32 (0x0b)
  Detected File System: FAT32
  Size: 64 MB (67108864 bytes)
  Start Sector: 2070121, Boot: No
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Reported Grub version:
  Could not detect Grub version
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'ThinStation'
  Size: 660.5 MB (Projected)
  Uses: EFI
Using image: thinstation-efi.iso (651.6 MB)

```

**Comment by pbatard** [comment] 2024-06-15 15:33
`Could not detect Grub version` is your issue.

It seems you built a custom GRUB that doesn't use a standard version, and as a result, since Rufus has to know what version it should use so it can install the proper USB/HDD GRUB bootloaders (since the ISO are **incompatible**) with USB/HDD boot and we can't just pick whatever `core.img` exists on the ISO and hope for the best (since a lot of ISO-provided `core.img` will be missing support for the file systems we need or the partition system, which we **cannot** load from separate submodules, and with compression, it's not like we can easily peek into the module to find out if it provides what we need or not).

Build a standard GRUB, that supplies a standard version (you can append a custom string, but if you do, make sure it is **appended** and that there is still the `x.y` version from the actual GRUB you used as your source), and you should find that your ISO works a lot better with Rufus (because, since hundreds of other GRUB-based Linux ISOs have no issue, why should yours, if you follow the same approach as these other folks do?).

**Comment by Thinstation** [comment] 2024-06-15 15:58
I'm sort of using a common grub. I was building 2.06, and applying the fedora/redhat patches. For some reason these strip the grub version. Beyond that, I'm not making any changes to grub. As you noted, the core.img can contain quite a lot or not enough, but perhaps we can assume that if they are provided by a vendor, they contain enough to get a disk up and running. This would negate the need to maintain a database of grub versions and builds on you end. I'm not opposed to using a naming convention that would let Rufus know that these are the files to be used. i.e. rufus-core.img etc..

**Comment by Thinstation** [comment] 2024-06-15 16:04
I should maybe also note that while I'm not using any crazy compilation of the binaries, I do embed a grub.cfg into core.img and I imagine that quite a few others do as well. I doubt there is any easy way for Rufus to account for that.

**Comment by pbatard** [comment] 2024-06-15 16:06
> and applying the fedora/redhat patches

I don't think you're applying all the Fedora/RH patches, because Rufus has no trouble detecting the GRUB version with Fedora images.

> But perhaps we can assume that if they are provided by a vendor, they contain enough to get a disk up and running.

No. As a matter of fact, Fedora need a "special" version of GRUB (see the `grub-2.06-nonstandard-gdie-fedora-##` at https://github.com/pbatard/rufus-web/tree/gh-pages/files) because they also apply custom patches, and we can't just pick a version that was designed purely for ISOHybrid boot and "hope" that somehow, the maintainers will have added modules that they don't need for ISOHybrid at all, just for the sake on utilities that don't use `dd` to write the image... which they rarely do.

> I'm not opposed to using a naming convention

You don't have to use a naming convention. You just have to fix the way you build and set up GRUB so that it does embed a version that can be parsed, like the GRUB binaries produced by Fedora do.

**Comment by Thinstation** [comment] 2024-06-15 16:09
This a snapshot of what I was doing, and at the time these patches removed the grub version. https://github.com/Thinstation/thinstation/blob/6.2-Stable/ts/ports/opt/grub2/Pkgfile
Maybe things have changed, we will see when I get 2.12 going

**Comment by pbatard** [comment] 2024-06-15 16:10
>  I do embed a grub.cfg into core.img and I imagine that quite a few others do as well.

None of the mainstream Linux distros do that, and you are the first person I hear from that does it. If you don't care about ensuring that users of your ISO can use the utility they want to write it, and force them to use `dd` or something, that's fine, but if you want to ensure compatibility with the widest of media creation tools, you should look into not doing that.

**Comment by pbatard** [comment] 2024-06-15 16:13
> This a snapshot of what I was doing, and at the time these patches removed the grub version.

Again, I can only state that Rufus is able to extract the GRUB version on standard Fedora ISOs, so you'll need to figure out how you deviate from the release builds, and sort that out. As you can understand, I can only ever invest time to support **mainstream** public ISOs and people who follow their design. If you customize your ISO in a super specific manner, things will break, and I am **not** going to try to patch Rufus so that it works just for your custom private design.

**Comment by Thinstation** [comment] 2024-06-15 16:18
I was actually hoping that as these files(core.img, maybe boot.img) can be highly customized, perhaps there is a way that Rufus can take them, if they are provided by a vendor, and run with them. While this would solve my issue, I think it might be of wider appeal to quite a few distro's, and actually reduce your burden(tracking down builds).

**Comment by pbatard** [comment] 2024-06-15 16:27
And then run into the current issue of distro maintainers deciding not to support NTFS at all (because they don't see the point), whereas it can actually be necessary if the distro uses symlinks, or deciding not to support GPT at all (because they don't see the point), whereas it can be desirable for the user to ensure that their media can only boot in pure UEFI mode. I have also some views into adding other GRUB modules that maintainers are unlikely to add in the future.

Unless I can sit behind each maintainer when they build their GRUB, and can force them to include specific modules, what you suggest is not a viable option, because people providing their own `core.img` will not be providing a `core.img` that is designed to work with Rufus, but a `core.img` that is designed to work with their limited set of conditions... **which is the precise issue you are running into because, for some reason, your `core.img` fails to provide a version that can be parsed by Rufus**.

So, again, not gonna happen. I will never, ever, rely on distro maintainers magically providing the modules and settings that are required for something they don't actually think they need. Plus, it's only for BIOS boot, which means a minority of end users (meaning, maintainers are even more likely to invest as little time as they can on that).

**Comment by Thinstation** [comment] 2024-06-15 16:33
Yeah, I know bios boot is long long overdue for retirement, but I still get pings on it. sigh* So we are at this weird crossroads, where you want to control the core.img build, but I(and other vendors) also need control of the core.img build, because a lot of things can be done there. Is there some way, other than hacking Rufus(by me), that a path can be made to work with Rufus to get all things done?

**Comment by pbatard** [comment] 2024-06-15 16:36
> Is there some way

Get enough end users to use your public ISO, and I **may** look into adding support for it. Outside of that, you'll have to invest your own time, and not expect much help from me or anybody else I'm afraid.

**Comment by Thinstation** [comment] 2024-06-15 16:43
I have over a million installations, but my primary users are admins, not end users. They take builds from my system and create deployments. It's used by the U.S. Government and was the basis for TENS and SecureView.

**Comment by pbatard** [comment] 2024-07-08 10:03
I'm going to close this issue for the reasons explained above and since we are not dealing with public ISOs.

**Closed by pbatard** 2024-07-08 10:03 UTC
