### ISSUE TITLE
Rufus 2.3 does not change the volume label 

### ISSUE THREAD

**Issue by Teflanzy** [pbatard/rufus#595] opened 2015-09-13 23:18 UTC
with rufus 2.2, the volume label will change automatically after selecting the iso image

but with rufus 2.3, the volume label is not changed after selecting the new iso image

 please fix this issue.

thanks for your hard work

**Comment by pbatard** [comment] 2015-09-13 23:57
Duplicate of #588 (which has already been patched and will be fixed in next version). Closing.

**Closed by pbatard** 2015-09-13 23:57 UTC
