### ISSUE TITLE
Error while accessing ldlinux.sys

### ISSUE THREAD

**Issue by flyingqube-dev** [pbatard/rufus#1747] opened 2021-06-03 19:41 UTC
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Help, there is something wrong with accessing ldlinux.sys

Log
Found USB 3.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
Found USB 3.0 device 'USB DISK 3.0 USB Device' (13FE:6300)
Removing F: from the list: This is the disk from which Rufus is running!
1 device found
Disk type: Removable, Disk size: 7.7GB, Sector size: 512 bytes
Cylinders: 940, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0066929B
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 7.2 GB (7735023616 bytes)
  Start Sector: 2048, Boot: Yes
Downloading https://rufus.ie/files/syslinux-6.04/20200816/ldlinux.sys
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.sys
File length: 66.5 KB
Successfully downloaded 'ldlinux.sys'
Download signature is valid ✓
Downloading https://rufus.ie/files/syslinux-6.04/20200816/ldlinux.bss
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'
Download signature is valid ✓

Format operation started
Requesting disk access...
Will use 'I:' as volume mountpoint
Deleting partitions:
● Partition 1 (offset: 1048576, size: 7.2 GB)
Opened \\.\PhysicalDrive4 for exclusive write access
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 7.2 GB)
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume \\?\Volume{a3d7f6fc-c3a8-11eb-a134-dc1ba1921f4d}\
Installing Syslinux 6.04...
Opened \\?\Volume{a3d7f6fc-c3a8-11eb-a134-dc1ba1921f4d} for shared write access
Could not open rufus_files/syslinux-6.04/20200816/ldlinux.sys
Re-mounted volume as I: after error

Found USB 3.0 device 'Kingston DataTraveler 3.0 USB Device' (0951:1666)
Found USB 3.0 device 'USB DISK 3.0 USB Device' (13FE:6300)
Removing F: from the list: This is the disk from which Rufus is running!
1 device found
Disk type: Removable, Disk size: 7.7GB, Sector size: 512 bytes
Cylinders: 940, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00680ECB
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)

<FULL LOG>
```

**Comment by pbatard** [comment] 2021-06-03 20:19
Nope, nothing wrong. Especially:

```
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.sys
File length: 66.5 KB
Successfully downloaded 'ldlinux.sys'
```
and
```
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'
Download signature is valid ✓
```
indicate that the files were successfully downloaded.

Please don't mistake expected 404 HTTP codes, that have to do with a fallback mechanism that allows us, __in very specific cases__, to override the generic Syslinux binary with a custom one, with actual errors.

The 404 you see are normal and in no way indicative of an issue. The files you need were also properly downloaded.

As such, since I don't see any evidence of a problem, I will close this issue.

**Closed by pbatard** 2021-06-03 20:19 UTC

**Comment by flyingqube-dev** [comment] 2021-06-03 20:22
I meant
`
Could not open rufus_files/syslinux-6.04/20200816/ldlinux.sys`
`Re-mounted volume as I: after error`

**Comment by flyingqube-dev** [comment] 2021-06-03 20:26
![image](https://user-images.githubusercontent.com/68196811/120707432-9a806900-c4ba-11eb-9f34-7a5c825a056d.png)
![image](https://user-images.githubusercontent.com/68196811/120707528-bc79eb80-c4ba-11eb-9830-1bc6932bd292.png)

**Comment by pbatard** [comment] 2021-06-03 20:30
Ah, I missed that.

Well, from what I can see the file you need should have been properly downloaded.

You did truncate the log though, which would have shown important information about the Syslinux version detected.

Can you re-create the media and make sure you copy paste the __full__ log, so that I have all the data needed to properly troubleshoot this issue? Especially, you did check the box that states that you copy/pasted the full log, which is not the case...

**Comment by flyingqube-dev** [comment] 2021-06-03 20:32
[rufus.log](https://github.com/pbatard/rufus/files/6594193/rufus.log)

**Comment by pbatard** [comment] 2021-06-03 20:33
That is __NOT__ the full log.

A full log starts with something like:
```
Rufus x86 v3.14.1788
Windows version: Windows 10 64-bit (Build 19043.985)
...
```

**Comment by flyingqube-dev** [comment] 2021-06-03 20:35
but it's all i have

**Comment by flyingqube-dev** [comment] 2021-06-03 20:35
alt+L

**Comment by flyingqube-dev** [comment] 2021-06-03 20:37
wait
i have one

**Comment by pbatard** [comment] 2021-06-03 20:37
Please read what I said. You need to recreate your media and then copy/paste the full log.
The log does start with `Rufus version: x.y.z` always. If you don't see that, you cleared or truncated it for whatever reason, and need to recreate your media. If you want help, it is crucial that I see the log data that you removed.

**Comment by flyingqube-dev** [comment] 2021-06-03 20:38
[rufus-proper log](https://github.com/pbatard/rufus/files/6594212/rufus-proper.log)

**Comment by flyingqube-dev** [comment] 2021-06-03 20:38
sorry

**Comment by pbatard** [comment] 2021-06-03 20:44
Aha:

```
Detected Syslinux version: 6.04/20200816 (from '/isolinux/isolinux.bin')
```

So Kali (why is it always them?) decided to start using slash in their version string. I suspect that this is the cause of the issue. I would really expect Kali folks to know better than use path characters for versioning, but I guess I'll just have to add more sanitizing.

Don't expect anything fast though.

**Comment by flyingqube-dev** [comment] 2021-06-03 20:46
Sure, thanks for patience.

**Comment by pbatard** [comment] 2021-06-03 20:50
Actually, that might not be it, as I tested an older Kali, that uses `Syslinux version: 6.03/20170128` and saw no issue. And I'm pretty sure I already added sanitization.

Especially, I got:

```
Using existing './rufus_files/syslinux-6.03/20170128/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/20170128/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Successfully wrote Syslinux boot record
```

Which means that there's no reason for your `rufus_files/syslinux-6.04/20200816/...` not to have been picked up.

Here is my log:
```
Rufus x86 v3.14.1788
Windows version: Windows 10 64-bit (Build 19043.985)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
0 devices found
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.03/20170128 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Kali Live'
  Size: 2.7 GB (Projected)
  Note: File on disk is larger than reported ISO size by 704 KB...
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.03
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Using image: kali-linux-rolling-amd64.iso (2.6 GB)
Found USB 3.0 device 'Mushkin Ventura Ultra USB Device' (174C:55AA)
1 device found
Disk type: FIXED, Disk size: 120 GB, Sector size: 512 bytes
Cylinders: 14593, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {83766410-FB89-4B6A-B22A-25D2DE6E79C6}
Max parts: 128, Start Offset: 17408, Usable = 120034089472 bytes
Partition 1:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  ID: {0401FC27-F41D-4D95-B7F9-0680D49F7F96}
  Size: 111.8 GB (120033058304 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Downloading https://rufus.ie/files/syslinux-6.03/20170128/ldlinux.sys
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.03/ldlinux.sys
File length: 67.0 KB
Successfully downloaded 'ldlinux.sys'
Download signature is valid ✓
Downloading https://rufus.ie/files/syslinux-6.03/20170128/ldlinux.bss
Unable to access file: 404
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.03/ldlinux.bss
File length: 512 bytes
Successfully downloaded 'ldlinux.bss'
Download signature is valid ✓

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Deleting partitions:
● Partition 1 (offset: 1048576, size: 111.8 GB)
Opened \\.\PhysicalDrive5 for exclusive write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 2176 sectors
Initializing disk...
Partitioning (MBR)...
● Creating Main Data Partition (offset: 1048576, size: 111.8 GB)
Waiting for logical drive to reappear...
Formatting (Large FAT32)...
Opened \\?\Volume{001b997d-0000-0000-0000-100000000000} for exclusive write access
Size : 111.8 GB 234439600 sectors
Cluster size 32768 bytes, 512 bytes per sector
Volume ID is 1d12:1c25
32 Reserved sectors, 28612 sectors per FAT, 2 FATs
3662224 Total clusters
3662223 Free clusters
Clearing out 57320 sectors for reserved sectors, FATs and root cluster...
Initializing reserved sectors and FATs...
FAT #0 sector at address: 32
FAT #1 sector at address: 28644
Writing Partition Boot Record...
Using Standard FAT32 partition boot record
Confirmed new volume has a primary FAT32 boot sector
Setting primary FAT32 boot sector for boot...
Confirmed new volume has a secondary FAT32 boot sector
Setting secondary FAT32 boot sector for boot...
Setting label...
Format completed.
Writing Master Boot Record...
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume \\?\Volume{001b997d-0000-0000-0000-100000000000}\
Installing Syslinux 6.03...
Opened \\?\Volume{001b997d-0000-0000-0000-100000000000} for shared write access
Using existing './rufus_files/syslinux-6.03/20170128/ldlinux.sys' ✓
Using existing './rufus_files/syslinux-6.03/20170128/ldlinux.bss' ✓
Successfully wrote 'ldlinux.sys'
Successfully wrote Syslinux boot record
Successfully remounted \\?\Volume{001b997d-0000-0000-0000-100000000000}\ as F:
Extracting files...
Image is an ISO9660 image
This image will be extracted using Rock Ridge extensions (if present)
Extracting: F:\.disk\archive_trace (1 bytes)
Extracting: F:\.disk\base_components (5 bytes)
Extracting: F:\.disk\base_installable (0 bytes)
Extracting: F:\.disk\cd_type (5 bytes)
Extracting: F:\.disk\info (100 bytes)
Extracting: F:\.disk\udeb_include (49 bytes)
Extracting: F:\autorun.inf (133 bytes)
Extracting: F:\boot\grub\dejavu-bold-14.pf2 (186.7 KB)
Extracting: F:\boot\grub\dejavu-bold-16.pf2 (207.2 KB)
Extracting: F:\boot\grub\efi.img (704 KB)
Extracting: F:\boot\grub\grub.cfg (3.4 KB)
Extracting: F:\boot\grub\i386-efi\acpi.mod (9.6 KB)
Extracting: F:\boot\grub\i386-efi\adler32.mod (1.3 KB)
Extracting: F:\boot\grub\i386-efi\ahci.mod (15.3 KB)
Extracting: F:\boot\grub\i386-efi\all_video.mod (500 bytes)
Extracting: F:\boot\grub\i386-efi\aout.mod (1 KB)
Extracting: F:\boot\grub\i386-efi\appleldr.mod (3.1 KB)
Extracting: F:\boot\grub\i386-efi\archelp.mod (3 KB)
Extracting: F:\boot\grub\i386-efi\ata.mod (5.7 KB)
Extracting: F:\boot\grub\i386-efi\at_keyboard.mod (4.2 KB)
Extracting: F:\boot\grub\i386-efi\backtrace.mod (1.6 KB)
Extracting: F:\boot\grub\i386-efi\bfs.mod (6.9 KB)
Extracting: F:\boot\grub\i386-efi\bitmap.mod (2.3 KB)
Extracting: F:\boot\grub\i386-efi\bitmap_scale.mod (3.7 KB)
Extracting: F:\boot\grub\i386-efi\blocklist.mod (2.2 KB)
Extracting: F:\boot\grub\i386-efi\boot.mod (2.1 KB)
Extracting: F:\boot\grub\i386-efi\bsd.mod (30.4 KB)
Extracting: F:\boot\grub\i386-efi\bswap_test.mod (2.4 KB)
Extracting: F:\boot\grub\i386-efi\btrfs.mod (14.5 KB)
Extracting: F:\boot\grub\i386-efi\bufio.mod (2.1 KB)
Extracting: F:\boot\grub\i386-efi\cat.mod (2.9 KB)
Extracting: F:\boot\grub\i386-efi\cbfs.mod (4.1 KB)
Extracting: F:\boot\grub\i386-efi\cbls.mod (3.5 KB)
Extracting: F:\boot\grub\i386-efi\cbmemc.mod (2.4 KB)
Extracting: F:\boot\grub\i386-efi\cbtable.mod (980 bytes)
Extracting: F:\boot\grub\i386-efi\cbtime.mod (2.8 KB)
Extracting: F:\boot\grub\i386-efi\chain.mod (5.2 KB)
Extracting: F:\boot\grub\i386-efi\cmdline_cat_test.mod (3 KB)
Extracting: F:\boot\grub\i386-efi\cmp.mod (2.0 KB)
Extracting: F:\boot\grub\i386-efi\cmp_test.mod (4.6 KB)
Extracting: F:\boot\grub\i386-efi\command.lst (3.6 KB)
Extracting: F:\boot\grub\i386-efi\cpio.mod (2.7 KB)
Extracting: F:\boot\grub\i386-efi\cpio_be.mod (2.8 KB)
Extracting: F:\boot\grub\i386-efi\cpuid.mod (1.7 KB)
Extracting: F:\boot\grub\i386-efi\crc64.mod (1.6 KB)
Extracting: F:\boot\grub\i386-efi\crypto.lst (936 bytes)
Extracting: F:\boot\grub\i386-efi\crypto.mod (5.0 KB)
Extracting: F:\boot\grub\i386-efi\cryptodisk.mod (10.1 KB)
Extracting: F:\boot\grub\i386-efi\cs5536.mod (3.8 KB)
Extracting: F:\boot\grub\i386-efi\ctz_test.mod (1.8 KB)
Extracting: F:\boot\grub\i386-efi\date.mod (2.2 KB)
Extracting: F:\boot\grub\i386-efi\datehook.mod (1.8 KB)
Extracting: F:\boot\grub\i386-efi\datetime.mod (1.2 KB)
Extracting: F:\boot\grub\i386-efi\disk.mod (2.4 KB)
Extracting: F:\boot\grub\i386-efi\diskfilter.mod (10.7 KB)
Extracting: F:\boot\grub\i386-efi\div.mod (1012 bytes)
Extracting: F:\boot\grub\i386-efi\div_test.mod (5.5 KB)
Extracting: F:\boot\grub\i386-efi\dm_nv.mod (1.8 KB)
Extracting: F:\boot\grub\i386-efi\echo.mod (1.9 KB)
Extracting: F:\boot\grub\i386-efi\efifwsetup.mod (1.5 KB)
Extracting: F:\boot\grub\i386-efi\efinet.mod (6 KB)
Extracting: F:\boot\grub\i386-efi\efi_gop.mod (7.8 KB)
Extracting: F:\boot\grub\i386-efi\efi_uga.mod (4.5 KB)
(...)
```

Can you please try <kbd>Alt</kbd>-<kbd>D</kbd> in Rufus, to delete the `rufus-files` directory and try again.
I'm not seeing much of a reason for your files not to be picked up...

**Comment by pbatard** [comment] 2021-06-03 20:53
Also, if that doesn't work, can you share a screenshot from file explorer of the content of `rufus_files\syslinux-6.04\20200816\`?

**Comment by flyingqube-dev** [comment] 2021-06-03 21:10
![image](https://user-images.githubusercontent.com/68196811/120712447-ee8e4c00-c4c0-11eb-949d-ff2196fa4a33.png)

**Comment by pbatard** [comment] 2021-06-03 21:26
So you are running Rufus from the root of your `F:` drive. What type of drive is it? Is it a physical drive/partition? Something else?

What happens if you try running Rufus from a folder of your `C:` drive. For instance, you can copy the Rufus executable to your desktop and see if it works better from there...

**Comment by flyingqube-dev** [comment] 2021-06-03 22:28
Well, F drive is my pendrive. I already checked and used both portable and normal versions, but both have the same problem. I tried to run it from another druve, ssd, but nothing changed

**Comment by flyingqube-dev** [comment] 2021-06-03 22:31
With c drive... wait until my morning (UTC+2)

**Comment by flyingqube-dev** [comment] 2021-06-04 08:06
Ok, i ran it from C: and now it works.

**Comment by flyingqube-dev** [comment] 2021-06-04 08:07
Maybe it was something with permissions?

**Comment by flyingqube-dev** [comment] 2021-06-04 08:10
![image](https://user-images.githubusercontent.com/68196811/120769127-16130200-c51d-11eb-9d94-4087f889f0e7.png)

**Comment by pbatard** [comment] 2021-06-04 18:38
Actually, this is a general issue when Rufus is running from the root of a drive, as I was able to replicate the problem on my machine.

From what I can see, the problem is that, in the Microsoft world, something like `chdir("F:\\")`works, whereas `chdir("F:")` doesn't, and in Rufus 3.14, we issue a [`_wchdir()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/chdir-wchdir) to the application directory, so that we can then reference the `rufus_files\` content.

And of course, in case our application resides on top of the drive, the API we use to locate the application directory ([`GetCurrentDirectory()`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getcurrentdirectory)) returns `"F:"` rather than `"F:\\", which makes `chdir()` fail. But as soon as Rufus resides inside a subdirectory of the drive, `chdir()` works.

Now the thing is that, with the commit that I pushed a few days before this issue was opened (9d7e96e293955b27b8424ce86a4490701484895b), this issue has actually become moot because Rufus 3.15 will stop placing downloads into a `rufus_files\` folder residing at the same level as the executable, to instead download into a `Rufus\` directory in `<user>\AppData\Local\` (in which case `chdir()` will work regardless of where the application resides).

But I think I'm going to make sure that I add a `\\` to the application directory string, if it's just a drive letter, just in case Microsoft has an other bad surprise in store with regards to how the data returned by one Windows API is not compatible with another Windows API...

**Comment by Srv-02** [comment] 2021-08-18 08:16
> Now the thing is that, with the commit that I pushed a few days before this issue was opened (9d7e96e293955b27b8424ce86a4490701484895b), this issue has actually become moot because Rufus 3.15 will stop placing downloads into a `rufus_files\` folder residing at the same level as the executable, to instead download into a `Rufus\` directory in `<user>\AppData\Local\` (in which case `chdir()` will work regardless of where the application resides).

Could you also please update the "Usage Notes" regarding "Where to manually copy the Syslinux/GRUB files, if Rufus can't download them"?
I was quite desperate that it didn't work anymore with v3.15 😁

**Comment by pbatard** [comment] 2021-08-18 10:14
> Could you also please update the "Usage Notes" regarding "Where to manually copy the Syslinux/GRUB files, if Rufus can't download them"?

Good point. I'll do that.
