### ISSUE TITLE
Feature request: More Windows 11 bypass Values

### ISSUE THREAD

**Issue by Myria-de** [pbatard/rufus#1881] opened 2022-03-04 07:11 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

Why not add all available registry entries for bypassing all hardware restrictions (Window 11)? BypassCPUCheck, BypassRAMCheck etc. Are there side effects with this? Thanks.

**Comment by pbatard** [comment] 2022-03-04 09:04
> - [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem

https://github.com/pbatard/rufus/issues?q=BypassCPUCheck where you would have found that your issue is a duplicate of #1791, #1809 and so on.

Closed as duplicate.

**Closed by pbatard** 2022-03-04 09:04 UTC
