### ISSUE TITLE
add Support for Hebrew

### ISSUE THREAD

**Issue by pinim** [pbatard/rufus#860] opened 2016-11-30 22:20 UTC
I want to help to translate into Hebrew, How Can I help it?

**Comment by pbatard** [comment] 2016-11-30 22:30
Please use existing #204 to register your interest and go for it. The way to proceed is detailed [here](https://github.com/pbatard/rufus/wiki/Localization). Also you might want to pay attention to how the Arabic or Persian translation are done, as right-to-left language require a few quirks when mixing English and non English. 

Now, since this is a duplicate of #204, I'm going to close this issue.

By the way, thanks for volunteering!
But please be mindful that translating Rufus is __a lot__ more work than people seem to imagine, and, surprisingly, all of the volunteers I've had for a Hebrew translation (and there have been quite a few now) appear to have given up after a while. Let's just hope you'll find motivated enough to complete it, as Hebrew is the very last language Rufus still needs to be translated into...

**Closed by pbatard** 2016-11-30 22:30 UTC

**Comment by NSbuilder** [comment] 2016-12-01 13:49
Here is my loc file - in case someone needs it: http://www77.zippyshare.com/v/tNc7e61O/file.html

**Comment by pbatard** [comment] 2016-12-01 14:19
Much appreciated!! I had a look at it and can see that you certainly spent a lot of time on this, so thank you very much.

I have now uploaded a slightly modified version of your translation [here](https://rufus.akeo.ie/testing/rufus_loc.7z), for any good soul who would like to complete your work.

**Comment by pinim** [comment] 2016-12-03 23:05
,I finished the translation

2016-12-01 16:19 GMT+02:00 Pete Batard <notifications@github.com>:

**Comment by pbatard** [comment] 2016-12-03 23:06
Can you please e-mail it to me? pete@akeo.ie

**Comment by pinim** [comment] 2016-12-03 23:09
I sent it

2016-12-04 1:06 GMT+02:00 Pete Batard <notifications@github.com>:

**Comment by pbatard** [comment] 2016-12-03 23:18
Got it. I'll take a look at it and let you know if there's anything that needs to be modified (this might take a couple of days).

Much appreciate the work you and NSbuilder did on that. At last, all the languages I wanted to be supported will be complete, and I'm sure many Hebrew speaking people will be very thankful for your efforts!

**Comment by pbatard** [comment] 2016-12-05 11:23
I have reviewed the Hebrew translation and found no issue 😄. It will be made available in the next version of Rufus.

Thanks again to the both of you for working on this!

**Comment by NSbuilder** [comment] 2017-01-17 15:08
I sent you the updated translation.
