### ISSUE TITLE
CHKDSK  cannot continue in read-only mode.

### ISSUE THREAD

**Issue by Gamboaman** [pbatard/rufus#379] opened 2014-10-06 20:34 UTC
Hi, I keep getting this error everytime I try formatting my flash drives for a windows 8.1. I have tried 2 different computers, and 2 different flash drives and ran it as administrator but can't quite figure out why it keeps giving me his error. Permissions for both flash drives have been set to EVERYONE, applied. Help?

```
CHKDSK cannot continue in read-only mode.
Media has been switched to read-only - Leaving checkdisk
Error while checking disk.
```

**Comment by passat1** [comment] 2015-12-15 11:25
Hi,
As it seems problem is with CHKDSK program.
It's similar as when "CHKDSK /F" is running and could not get exclusive access to disk while any other program is using this disk or files on it.
Try to close ALL other programs and ALL explorer windows before starting format in Rufus.
Temporary disable antivirus too, as it can also be one who's accessing files at that moment.

**Comment by Boomhauer1** [comment] 2016-12-23 06:49
I had this pop up starting today. I used RUFUS to write a file 5 months ago and it worked fine. I use it today and now I have two unusable usb drives, by separate manufacturers, which are two separate sizes. One is  stuck as write protected with nothing available on the internet (that I could find) able to fix it. The other one is no longer recognized on any of my computers. There has been no change in this computer since 5 months ago apart from windows/chrome/steam updates.


The drive is unrecoverable in other computers. I would run a log but I do not want to lose anymore usb drives at this point because I am fairly certain I will get the same end result.  You claim it is incredibly difficult to damage usb drives. Yet it appears that somehow your program excels at that on my computer. Have you been able to come up with any solutions in the last 2 years?

**Comment by Boomhauer1** [comment] 2016-12-23 07:01
Additionally, this had nothing to do with a hardware failure. I understand that any solid state media has a limited number of write cycles. One of the drives is 8gb that I bought 8 months ago. I have written a total of around 50gb total to it on the high side. The second is a 5 year old 32gb which has had at least 400gb written to it. I could accept the older one dying, but not the new one. I can find it's "sister" drive which I bought the same day, has never been used. But I do not really wish to have yet another drive die on me due to this "safe" program.

**Comment by pbatard** [comment] 2016-12-23 10:31
> You claim it is incredibly difficult to damage usb drives.

I do stand by what I wrote [here](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive).
Even if Rufus has a major bug, it is simply not possible for it to damage drives. As a matter of fact, I'd really like anybody who wants to claim otherwise to propose an explanation as to how this would be possible, because as far as what Rufus is able to access, __THERE IS NO SPECIAL SECTOR ON AN USB DRIVE THAT CAN INCUR DAMAGE IF WRITTEN IMPROPERLY__.

The __ONLY__ way I know to render a drive inoperable is if you send a set of exceedingly specific manufacturer commands. So you may think that maybe there's a bug in Rufus that somehow allows it to send these unwanted commands. However, even if you happened to know the manufacturer specific sequence to send to a drive to render it inoperable, it should simply not possible to do so through the Windows Mass Storage driver, which is the only one Rufus uses (and in a indirect manner at that).

I really have to stress the following. The __ONLY__ advanced operation Rufus does with a drive is to sometime ask Windows (and NOT the drive or even the mass storage driver) something like `write n bytes into the sector at address #`. That's really the most low level stuff Rufus ever does to any USB drive, and I will encourage anyone who doesn't believe this to have a look at the source if they aren't convinced that this is as far as Rufus goes when it comes to low level operations. And then there's the USB enumeration part, which is really Rufus asking Windows (and NOT the USB drives) to report a list and the properties of the devices it detected as connected. Provided Windows does a half decent job at remembering which devices are attached, the enumeration does not incur any USB transfers (and even if it does, you can hardly call something as an USB transfer that is generated by the Windows OS alone as something risky).

Which of course leads us to the following conclusion:
__If you look at it logically, and have some minimal knowledge of what goes into enumerating/partitioning/reformatting/writing to a drive on Windows, it just isn't possible for Rufus to damage USB flash drives__

> this had nothing to do with a hardware failure.

I very much beg to differ. As much as you would like to pretend otherwise, any other explanation is exceedingly unlikely.

> I understand that any solid state media has a limited number of write cycles.

Yes, but it doesn't work the way you posit, which is "media will only fail after n number of cycles". because of the laws of probabilities and the relatively short life time of flash memory, Media can and does happen to fail much earlier than people imagine, if you're slightly unlucky (or you bought cheap media).

> But I do not really wish to have yet another drive die on me due to this "safe" program.

Feel free to convince yourself that Rufus is unsafe. I guess it's easier to admit than the fact that you just have been unlucky (or that maybe your hardware environment is inducing these failures). But you do realize that, if it's really Rufus that is the issue, and, as some people seem to be believing, I'm trying to cover up a major bug that I know is there, with the program being open source, being downloaded more than 3 million times a month, and the relative availability of USB traffic analyzers, there should have been someone with the expertise to demonstrate that Rufus happens to have a bug that can destroy flash drives. Heck, if the problem is even as remotely widespread as some people expect it to be (_"I happened to lose 2 drives while using Rufus therefore other Rufus users are __guaranteed__ to also lose drives when they use it"_), then I'm sure that flash drive manufacturers, who would no doubt receive the mirror kind of complaint from the one you make; that their drive was of subpar quality because it failed while they were using Rufus, would be eager to demonstrate that their drive's quality was not the factor at hand, and that Rufus is the culprit. Yet, Rufus continues to be downloaded millions and millions of times, and yet, none of that has happened...

So, I'm sorry, but contrary to what you'd like to establish, there actually does exist ample evidence that Rufus __IS__ safe to use, and that it will not destroy flash drives, no matter how much of a lousy programmer (as well as a devious person, since the few vocal people who want to point the finger at Rufus think that I'm conspiring to hide _the truth_) you think its developer is.

**Comment by Boomhauer1** [comment] 2016-12-23 20:41
You claim that it is impossible to damage any drives. Yet I stand by it. Using the program has the possibility to damage a drive. Even though the chances are incredibly rare. 

I only brought up the write cycles because in your FAQ it says that if a drive dies, it just might to happen to have coincided with using rufus. Which is why after the first drive died. I used a drive by a different manufacturer with different amounts of write cycles. I tried rufus again this morning on a brand new usb drive.  I stupidly did not get a log but am now the proud owner of another write protected drive.  I did originally test it by loading on a 5MB song on it.  If I find another usb drive lying (that is not pny or lexar) around I will get a log and use a different computer.

I never said this was your plan to destroy drives or any of those other claims of other people.  Where the hell did I ever say other users are guaranteed to lose drives? I do not care how many downloads/complaints/month you get. You are aware that not everyone is willing to go through the effort to report anything? I was looking for a solution for a few hours before I finally made this post. Even then I expected this response. "The problem is you, not my program". If someone had their drive die, and then fixed it, they probably wouldn't post on here. Most people would sooner move to a new program which worked for them and forget about the previous one. 

I did try other solutions I could find but nothing worked. Since none of the other solutions worked, I was hoping someone had something else they had tried and fixed it. The FAQ says that it means the drive is probably dead if it is write protected. Which is a a bad luck of the draw to just so happen have it after using this program. Even when eventually using a new flash drive. It must have been a bad batch of flash drives. Rufus worked in the past to write many iso files using this exact hardware. One of those previously used drives is identical drive to the one which died yesterday. This computer has had software updates but nothing major. I was "asking" (I didn't clearly ask) if someone else knew how to remove the write protection from the flash drive. Assuming they aren't dead, like I am thinking it is.

**Comment by pbatard** [comment] 2016-12-23 22:11
Fair enough. But please try to understand that the bulk of comments I have received in the past, when someone happened to lose their drive while using Rufus was: _"I'm sure that your program did it! And no matter what you say, I'm convinced that you are trying to cover up a major bug here..."_, which, though it doesn't happen that often, has gotten exceedingly annoying when it mostly comes from people who appear to have little idea how disk/volume level drive access work in Windows, and believe that there's some critical aspect to it when it applies to USB Flash Drives...

I do understand that, if you happen to lose a drive while using Rufus (or multiple ones, which is strange, but can still be explained through external causes, especially if you are using PNY drives &mdash; more about this bellow), you are going to be very suspicious of the application you were using at the time of the failure . However, the totality of Rufus source code is in the open, and with millions of users, I would say that there's bound to have been quite a few developers (or hardware manufactures) out there who have had a closer look at what Rufus does, and would be able to point out such a catastrophic issue as one that would result in dead drives, even if occasionally.

Now, with regards to trying to help you out, you happen to mention PNY (even though I understand that the other drive that failed was a Lexar), and one thing I am aware of is that PNY have had an issue with the firmware of some of their USB flash drives (mostly for PNY 16GB Retract USB, but other models might be affected), and that may result in an inoperable drive unless you update that firmware. This is something I mention at the very end of the FAQ (in the compatibility section), and maybe you might be able to salvage your drive with the tools provided [here](http://www.pny.com/support/technical-support/usb-flash-drives/16gb-retract-usb-firmware) or [here](http://www.pny.com.tw/index.php?cls=2&mode=download). At this stage, I am however not aware of manufacturer issues with Lexar drives.

The other advice I can give is to first try to reformat your drive from a Linux machine, just in case, as, for instance, I've seen some weird behaviour of Windows with Chromium images that contain a lot of GPT partitions (which I eventually demonstrated had nothing to do with Rufus, as the same issue happened even when issuing a `dd` from Linux), with Windows refusing to recognize the drive after writing to it, and the only way to recover the drive being to repartition it in Linux (#759). So, yeah, Windows does happen to have a few bugs on its own, without Rufus needing to introduce its own, if you're unlucky enough to partition your flash drive in a manner that Microsoft doesn't like.

Finally, your last recourse if none of the above applies, it to try to hunt down the __custom and very private__ manufacturer tools  for specific brands of USB flash drives, which you might use to try to reset the firmware, and which may (usually temporarily) help you recover its functionality. However, these tools are almost never made public, and are therefore incredibly hard to track. For what is worth, I have never managed to get my hands on one of these tools, for any of the flash drives I own. But who knows, you might get lucky.

**Comment by pbatard** [comment] 2017-02-16 16:15
I'm going to close this issue. In many years of Rufus development and usage, against all sorts of drives, I have never ever encountered this issue, and I'm not seeing many reports of it. As I am not in any position to investigate this problem, which logically appears to be external to Rufus, it doesn't make sense to keep this issue open.

**Closed by pbatard** 2017-02-16 16:15 UTC
Labels: deferred
