### ISSUE TITLE
Software connection is not available

### ISSUE THREAD

**Issue by dsapr** [pbatard/rufus#1399] opened 2019-10-29 03:16 UTC
Hi, the software can not be downloaded in the official website, trouble check whether it is deployed, and can not find your md5 in the third-party download is not the original version.

Chinese：
hi,软件在官网无法下载，麻烦检查一下是不是部署出问题了，在第三方下载也找不到你们的md5查看是不是原版。

**Comment by pbatard** [comment] 2019-10-29 10:03
The downloads from https://rufus.ie/ and https://github.com/pbatard/rufus/releases work just fine. Therefore, if you can't download it, then the issue is on your side. Also, because Rufus is digitally signed, providing an MD5 would be completely superfluous, since its SHA-256 is verified automatically by Windows as part of the digital signature validation process.

&rarr; Closing

**Closed by pbatard** 2019-10-29 10:03 UTC
