### ISSUE TITLE
windows11 formatting error

### ISSUE THREAD

**Issue by fachocn** [pbatard/rufus#2411] opened 2024-01-23 11:39 UTC
Hello, I have tried several versions and they all display "formatting error". How can I solve this problem? thanks

```
Rufus x64 v4.4.2103 (Portable)
Windows version: Windows 11 Home China x64 (Build 22621.3007)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0804 (zh-CN)
Will use default UI locale 0x0804
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-CN'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:125D)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 536 GB, Sector size: 512 bytes
Cylinders: 65270, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {3B5658BC-E06E-404D-9379-B57D25E55B6E}
Max parts: 128, Start Offset: 17408, Usable = 536871926272 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: (Unrecognized)
  ID: {00C1EBEB-FA98-4AD8-B569-CABA014A9478}
  Size: 260 MB (272629760 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: Microsoft System Reserved Partition
  Name: 'Microsoft Reserved Partition'
  Detected File System: (Unrecognized)
  ID: {B4358326-05BF-4237-9EF7-BCC43E1E71C4}
  Size: 128 MB (134217728 bytes)
  Start Sector: 534528, Attributes: 0x0000000000000000
Partition 3:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: (Unrecognized)
  ID: {F45C1E90-5337-44DE-8099-88DD20A2D613}
  Size: 499.6 GB (536464044032 bytes)
  Start Sector: 796672, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CPBA_A64FRE_ZH-CN_DV9'
  Detected: Windows 11 ISO (Build 22621.2428)
  Size: 6.6 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (UEFI only)
  Uses: Install.wim (version 0.13.1)
Using image: SW_DVD9_Win_Pro_11_23H2_Arm64_ChnSimp_Pro_Ent_EDU_N_MLF_X23-59518.ISO (6.7 GB)
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Opening: \\.\CDROM0/sources/install.wim:[0] (API)
Extracting: C:\Users\facho\AppData\Local\Temp\Ruf2C8F.tmp (From [1].xml)
Closing: \\.\CDROM0/sources/install.wim
Will use 'Windows 11 专业版' (Build: 22621, Index 2) for Windows To Go
Selected Windows User Experience options:
• Bypass online account requirement
• Set internal drives offline

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Opened \\.\PhysicalDrive2 for shared write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating EFI System Partition (offset: 1048576, size: 260 MB)
● Creating Microsoft Reserved Partition (offset: 273678336, size: 128 MB)
● Creating Main Data Partition (offset: 407896064, size: 499.6 GB)
Waiting for logical drive to reappear...
Formatting to NTFS (using IFS)
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
[0x00000002] The system cannot find the file specified. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
Format error: Undetermined error while formatting.
Re-mounted volume as F: after error

Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:125D)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 536 GB, Sector size: 512 bytes
Cylinders: 65270, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {9A14ACA8-3F39-40D9-8F09-222B70285E10}
Max parts: 128, Start Offset: 17408, Usable = 536871926272 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: (Unrecognized)
  ID: {613C88B7-B82E-4A7D-92D3-5966B23CFA59}
  Size: 260 MB (272629760 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: Microsoft System Reserved Partition
  Name: 'Microsoft Reserved Partition'
  Detected File System: (Unrecognized)
  ID: {2CA65C83-BA57-425A-875E-13319F7527EF}
  Size: 128 MB (134217728 bytes)
  Start Sector: 534528, Attributes: 0x0000000000000000
Partition 3:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: (Unrecognized)
  ID: {EA895B93-EF02-4D73-89F4-95AC91F01C38}
  Size: 499.6 GB (536464044032 bytes)
  Start Sector: 796672, Attributes: 0x0000000000000000
```

![image](https://github.com/pbatard/rufus/assets/62379246/bc853c13-fd8d-487f-a5c6-8601204b7a68)

**Comment by pbatard** [comment] 2024-01-23 11:42
Per the checklist:
---------

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.


At least, please run the bad blocks check, as you were requested.

**Comment by fachocn** [comment] 2024-01-24 02:31
@pbatard 
Hello, I conducted a night long bad block detection yesterday and it was reported that there were 287 pieces. I am currently using a TF card, can this situation still be repaired? Also, I bought a Sata solid-state drive case and will try it again tomorrow or the day after the delivery arrives.


Rufus x64 v4.4.2103 (Portable)
Windows version: Windows 11 Home China x64 (Build 22621.3007)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0804 (zh-CN)
Will use default UI locale 0x0804
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'zh-CN'
Notice: The ISO download feature has been deactivated because 'Check for updates' is disabled in your settings.
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:125D)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 536 GB, Sector size: 512 bytes
Cylinders: 65270, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {9A14ACA8-3F39-40D9-8F09-222B70285E10}
Max parts: 128, Start Offset: 17408, Usable = 536871926272 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: (Unrecognized)
  ID: {613C88B7-B82E-4A7D-92D3-5966B23CFA59}
  Size: 260 MB (272629760 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: Microsoft System Reserved Partition
  Name: 'Microsoft Reserved Partition'
  Detected File System: (Unrecognized)
  ID: {2CA65C83-BA57-425A-875E-13319F7527EF}
  Size: 128 MB (134217728 bytes)
  Start Sector: 534528, Attributes: 0x0000000000000000
Partition 3:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: (Unrecognized)
  ID: {EA895B93-EF02-4D73-89F4-95AC91F01C38}
  Size: 499.6 GB (536464044032 bytes)
  Start Sector: 796672, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is a UDF image
Disk image analysis:
  Image does not have a Boot Marker
ISO label: 'CPBA_A64FRE_ZH-CN_DV9'
  Detected: Windows 11 ISO (Build 22621.2428)
  Size: 6.6 GB (Projected)
  Has a >4GB file
  Uses: EFI
  Uses: Bootmgr (UEFI only)
  Uses: Install.wim (version 0.13.1)
Using image: SW_DVD9_Win_Pro_11_23H2_Arm64_ChnSimp_Pro_Ent_EDU_N_MLF_X23-59518.ISO (6.7 GB)
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Opening: \\.\CDROM0/sources/install.wim:[0] (API)
Extracting: C:\Users\facho\AppData\Local\Temp\Ruf542C.tmp (From [1].xml)
Closing: \\.\CDROM0/sources/install.wim
Will use 'Windows 11 专业版' (Build: 22621, Index 2) for Windows To Go
Selected Windows User Experience options:
• Bypass online account requirement
• Set internal drives offline

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Opened \\.\PhysicalDrive2 for shared write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Partitioning (GPT)...
● Creating EFI System Partition (offset: 1048576, size: 260 MB)
● Creating Microsoft Reserved Partition (offset: 273678336, size: 128 MB)
● Creating Main Data Partition (offset: 407896064, size: 499.6 GB)
Waiting for logical drive to reappear...
Formatting to NTFS (using IFS)
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
[0x00000002] The system cannot find the file specified. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
Format error: Undetermined error while formatting.
Re-mounted volume as F: after error

Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:125D)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 536 GB, Sector size: 512 bytes
Cylinders: 65270, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {3BB273D7-F01F-4BD6-B37B-ED8E61C007F7}
Max parts: 128, Start Offset: 17408, Usable = 536871926272 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: (Unrecognized)
  ID: {004A6E5A-54DF-4458-AAE5-B2941D20EF56}
  Size: 260 MB (272629760 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: Microsoft System Reserved Partition
  Name: 'Microsoft Reserved Partition'
  Detected File System: (Unrecognized)
  ID: {E83A8420-D515-49F0-9BE9-9FA324CFBE11}
  Size: 128 MB (134217728 bytes)
  Start Sector: 534528, Attributes: 0x0000000000000000
Partition 3:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: (Unrecognized)
  ID: {4F72E1A8-D2B6-45F6-B4E9-BB8F5D0079CA}
  Size: 499.6 GB (536464044032 bytes)
  Start Sector: 796672, Attributes: 0x0000000000000000
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Opening: \\.\CDROM0/sources/install.wim:[0] (API)
Extracting: C:\Users\facho\AppData\Local\Temp\Ruf2D8F.tmp (From [1].xml)
Closing: \\.\CDROM0/sources/install.wim
Will use 'Windows 11 专业版' (Build: 22621, Index 2) for Windows To Go
Selected Windows User Experience options:
• Bypass online account requirement
• Set internal drives offline

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Opened \\.\PhysicalDrive2 for shared write access
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Initializing disk...
Bad Blocks: Checking from block 0 to 1024001 (1 block = 512 KB)
Bad Blocks: Using offset 12592 for fake device check
Bad Blocks: Writing test pattern 0x55
Bad Blocks: Reading and comparing
Bad Blocks: 85174
Bad Blocks: 89998
Bad Blocks: 91942
Bad Blocks: 96982
Bad Blocks: 97485
Bad Blocks: 118869
Bad Blocks: 119975
Bad Blocks: 119976
Bad Blocks: 119977
Bad Blocks: 119978
Bad Blocks: 119979
Bad Blocks: 119980
Bad Blocks: 119981
Bad Blocks: 119982
Bad Blocks: 119983
Bad Blocks: 119984
Bad Blocks: 119985
Bad Blocks: 119986
Bad Blocks: 119987
Bad Blocks: 119988
Bad Blocks: 119989
Bad Blocks: 119990
Bad Blocks: 119991
Bad Blocks: 119992
Bad Blocks: 119993
Bad Blocks: 119994
Bad Blocks: 119995
Bad Blocks: 119996
Bad Blocks: 119997
Bad Blocks: 119998
Bad Blocks: 119999
Bad Blocks: 120000
Bad Blocks: 120001
Bad Blocks: 120002
Bad Blocks: 120003
Bad Blocks: 120004
Bad Blocks: 120005
Bad Blocks: 120006
Bad Blocks: 120007
Bad Blocks: 120008
Bad Blocks: 120009
Bad Blocks: 120010
Bad Blocks: 120011
Bad Blocks: 120012
Bad Blocks: 120013
Bad Blocks: 120014
Bad Blocks: 120015
Bad Blocks: 120016
Bad Blocks: 120017
Bad Blocks: 120018
Bad Blocks: 120019
Bad Blocks: 120020
Bad Blocks: 120021
Bad Blocks: 120022
Bad Blocks: 120023
Bad Blocks: 120024
Bad Blocks: 120025
Bad Blocks: 120026
Bad Blocks: 120027
Bad Blocks: 120028
Bad Blocks: 120029
Bad Blocks: 120030
Bad Blocks: 120031
Bad Blocks: 120032
Bad Blocks: 120033
Bad Blocks: 120034
Bad Blocks: 120035
Bad Blocks: 120036
Bad Blocks: 120037
Bad Blocks: 120038
Bad Blocks: 120039
Bad Blocks: 120040
Bad Blocks: 120041
Bad Blocks: 120042
Bad Blocks: 120043
Bad Blocks: 120044
Bad Blocks: 120045
Bad Blocks: 120046
Bad Blocks: 120047
Bad Blocks: 120048
Bad Blocks: 120049
Bad Blocks: 120050
Bad Blocks: 120051
Bad Blocks: 120052
Bad Blocks: 120053
Bad Blocks: 120054
Bad Blocks: 120055
Bad Blocks: 120056
Bad Blocks: 120057
Bad Blocks: 120058
Bad Blocks: 120059
Bad Blocks: 120060
Bad Blocks: 120061
Bad Blocks: 120062
Bad Blocks: 120063
Bad Blocks: 120064
Bad Blocks: 120065
Bad Blocks: 120066
Bad Blocks: 120067
Bad Blocks: 120068
Bad Blocks: 120069
Bad Blocks: 120070
Bad Blocks: 120071
Bad Blocks: 120072
Bad Blocks: 120073
Bad Blocks: 120074
Bad Blocks: 120075
Bad Blocks: 120076
Bad Blocks: 120077
Bad Blocks: 120078
Bad Blocks: 120079
Bad Blocks: 120080
Bad Blocks: 120081
Bad Blocks: 120082
Bad Blocks: 120083
Bad Blocks: 120084
Bad Blocks: 120085
Bad Blocks: 120086
Bad Blocks: 120087
Bad Blocks: 120088
Bad Blocks: 120089
Bad Blocks: 120090
Bad Blocks: 120091
Bad Blocks: 120092
Bad Blocks: 120093
Bad Blocks: 120094
Bad Blocks: 120095
Bad Blocks: 120096
Bad Blocks: 120097
Bad Blocks: 120098
Bad Blocks: 120099
Bad Blocks: 120100
Bad Blocks: 120101
Bad Blocks: 120102
Bad Blocks: 120103
Bad Blocks: 120104
Bad Blocks: 120105
Bad Blocks: 120106
Bad Blocks: 120107
Bad Blocks: 120108
Bad Blocks: 120109
Bad Blocks: 120110
Bad Blocks: 120111
Bad Blocks: 120112
Bad Blocks: 120113
Bad Blocks: 120114
Bad Blocks: 120115
Bad Blocks: 120116
Bad Blocks: 120117
Bad Blocks: 120118
Bad Blocks: 120119
Bad Blocks: 120120
Bad Blocks: 120121
Bad Blocks: 120122
Bad Blocks: 120123
Bad Blocks: 120124
Bad Blocks: 120125
Bad Blocks: 120126
Bad Blocks: 120127
Bad Blocks: 120128
Bad Blocks: 120129
Bad Blocks: 120130
Bad Blocks: 120131
Bad Blocks: 120132
Bad Blocks: 120133
Bad Blocks: 120134
Bad Blocks: 120135
Bad Blocks: 120136
Bad Blocks: 120137
Bad Blocks: 120138
Bad Blocks: 120139
Bad Blocks: 120140
Bad Blocks: 120141
Bad Blocks: 120142
Bad Blocks: 120143
Bad Blocks: 120144
Bad Blocks: 120145
Bad Blocks: 120146
Bad Blocks: 120147
Bad Blocks: 120148
Bad Blocks: 120149
Bad Blocks: 120150
Bad Blocks: 120151
Bad Blocks: 120152
Bad Blocks: 120153
Bad Blocks: 120154
Bad Blocks: 120155
Bad Blocks: 120156
Bad Blocks: 120157
Bad Blocks: 120158
Bad Blocks: 120159
Bad Blocks: 120160
Bad Blocks: 120161
Bad Blocks: 120162
Bad Blocks: 120163
Bad Blocks: 120164
Bad Blocks: 120165
Bad Blocks: 120166
Bad Blocks: 120167
Bad Blocks: 120168
Bad Blocks: 120169
Bad Blocks: 120170
Bad Blocks: 120171
Bad Blocks: 120172
Bad Blocks: 120173
Bad Blocks: 120174
Bad Blocks: 120175
Bad Blocks: 120176
Bad Blocks: 120177
Bad Blocks: 120178
Bad Blocks: 120179
Bad Blocks: 120180
Bad Blocks: 120181
Bad Blocks: 120182
Bad Blocks: 120183
Bad Blocks: 120184
Bad Blocks: 120185
Bad Blocks: 120186
Bad Blocks: 120187
Bad Blocks: 120188
Bad Blocks: 120189
Bad Blocks: 120190
Bad Blocks: 120191
Bad Blocks: 120192
Bad Blocks: 120193
Bad Blocks: 120194
Bad Blocks: 120195
Bad Blocks: 120196
Bad Blocks: 120197
Bad Blocks: 120198
Bad Blocks: 120199
Bad Blocks: 120200
Bad Blocks: 120201
Bad Blocks: 120202
Bad Blocks: 120203
Bad Blocks: 120204
Bad Blocks: 120205
Bad Blocks: 120206
Bad Blocks: 120207
Bad Blocks: 120208
Bad Blocks: 120209
Bad Blocks: 120210
Bad Blocks: 120211
Bad Blocks: 120212
Bad Blocks: 120213
Bad Blocks: 120214
Bad Blocks: 120215
Bad Blocks: 120216
Bad Blocks: 120217
Bad Blocks: 120218
Bad Blocks: 120219
Bad Blocks: 120220
Bad Blocks: 120221
Bad Blocks: 120222
Bad Blocks: 120223
Bad Blocks: 120224
Bad Blocks: 120225
Bad Blocks: 120226
Bad Blocks: 120227
Bad Blocks: 120228
Bad Blocks: 120229
Bad Blocks: 120230
Bad Blocks: 120231
Bad Blocks: 120232
Bad Blocks: 120233
Bad Blocks: 120234
Bad Blocks: 120235
Bad Blocks: 120236
Bad Blocks: 120237
Bad Blocks: 120238
Bad Blocks: 120239
Bad Blocks: 120240
Bad Blocks: 120241
Bad Blocks: 120242
Bad Blocks: 120243
Bad Blocks: 120244
Bad Blocks: 120245
Bad Blocks: 120246
Bad Blocks: 120247
Bad Blocks: 120248
Bad Blocks: 120249
Bad Blocks: 120250
Bad Blocks: 120251
Bad Blocks: 120252
Bad Blocks: 120253
Bad Blocks: 120254
Bad Blocks: 120255
Too many bad blocks, aborting test
Bad Blocks: Check completed, 287 bad blocks found. (0/0/287 errors)
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (GPT)...
● Creating EFI System Partition (offset: 1048576, size: 260 MB)
● Creating Microsoft Reserved Partition (offset: 273678336, size: 128 MB)
● Creating Main Data Partition (offset: 407896064, size: 499.6 GB)
Waiting for logical drive to reappear...
Formatting to NTFS (using IFS)
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Error while formatting
[0x00000002] The system cannot find the file specified. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
[0x0000012A] Too many posts were made to a semaphore. - Retrying...
Format error: Undetermined error while formatting.
Re-mounted volume as F: after error

Found USB 2.0 device 'Mass Storage Device USB Device' (14CD:125D)
1 device found
No volume information for drive 0x82
Disk type: Removable, Disk size: 536 GB, Sector size: 512 bytes
Cylinders: 65270, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {501E5155-CAD9-4EA7-A761-2BEB3DEED0CA}
Max parts: 128, Start Offset: 17408, Usable = 536871926272 bytes
Partition 1:
  Type: EFI System Partition
  Name: 'EFI System Partition'
  Detected File System: (Unrecognized)
  ID: {87E7EB15-B792-47F3-887C-80A0A23A88B4}
  Size: 260 MB (272629760 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: Microsoft System Reserved Partition
  Name: 'Microsoft Reserved Partition'
  Detected File System: (Unrecognized)
  ID: {A67F8CCE-397E-42D4-BF7C-4304BF9049B4}
  Size: 128 MB (134217728 bytes)
  Start Sector: 534528, Attributes: 0x0000000000000000
Partition 3:
  Type: Microsoft Basic Data Partition
  Name: 'Main Data Partition'
  Detected File System: (Unrecognized)
  ID: {8AA86CB0-7C69-43E3-95A7-076F7BDC77B1}
  Size: 499.6 GB (536464044032 bytes)
  Start Sector: 796672, Attributes: 0x0000000000000000

**Comment by pbatard** [comment] 2024-01-24 02:34
> I conducted a night long bad block detection yesterday and it was reported that there were 287 pieces

That __is__ your issue. And Rufus stops reporting bad blocks when it detects more than a specific number.

> can this situation still be repaired?

No. If you value your data and your time, you should consider that your media is irreversibly damaged when a bad blocks test report multiple defective block.

Because bad media is clearly the cause of all your problems, I will close this issue.

**Closed by pbatard** 2024-01-24 02:34 UTC
