### ISSUE TITLE
Error reading UDF file /Sources/OEM/AfterImage.CMD

### ISSUE THREAD

**Issue by KohaviZ** [pbatard/rufus#846] opened 2016-10-26 15:45 UTC
I have another computer which had it's hard disk switched to an empty one. Dell gave me a windos ISO file that is made for that computer. I am using another computer to make a bootable usb with the ISO on it but I get an error from Rufus.

Heres the log:
```
Rufus version: 2.11.995
Windows version: Windows 10 64-bit (Build 14393)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x040D
Detected installed Windows Language Pack for 0x0409 (English (English))
0 devices found
Scanning image...
ISO analysis:
  Image is an UDF image
Could not locate file /sources/install.swm in ISO image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'W10_x64'
  Size: 4294963200 bytes
  Uses: EFI
  Uses: Bootmgr
  Uses: Install.wim (version 255.255.255)
  Note: This WIM version is NOT compatible with Windows To Go
Using image: 9663HA00_W10x64ROW_home(DL)_v3.iso
Found USB 2.0 device 'SanDisk Cruzer Blade USB Device' (0781:5567)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3800, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {53873819-D506-4588-A65B-0B843D394A37}
Max parts: 128, Start Offset: 17408, Usable = 31260670464 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {0E939770-033C-4816-A87E-05AC8557EDC4}
  Size: 29.1 GB (31259639296 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Found USB 2.0 device 'SanDisk Cruzer Blade USB Device' (0781:5567)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3800, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {53873819-D506-4588-A65B-0B843D394A37}
Max parts: 128, Start Offset: 17408, Usable = 31260670464 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {0E939770-033C-4816-A87E-05AC8557EDC4}
  Size: 29.1 GB (31259639296 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'E:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (GPT)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 16384 bytes
Quick format was selected
Creating file system...
Format completed.
Found volume GUID \\?\Volume{03d6d563-9b84-11e6-89cc-bc8556de6b66}\
Successfully remounted Volume{03d6d563-9b84-11e6-89cc-bc8556de6b66}\ on E:\
Copying ISO files...
Extracting files...
Image is an UDF image
Extracting: E:\Sources\BOOT.wim (577.3 MB)
Extracting: E:\Sources\OEM\AfterImage.CMD (2.1 KB)
  Error reading UDF file /Sources/OEM/AfterImage.CMD

Found USB 2.0 device 'SanDisk Cruzer Blade USB Device' (0781:5567)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3800, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: GPT, NB Partitions: 1
Disk GUID: {3B2EA530-4080-4380-BFFE-F2782EEE8395}
Max parts: 128, Start Offset: 17408, Usable = 31260670464 bytes
Partition 1:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Microsoft Basic Data'
  ID: {DCFA9DE9-D89D-452F-B4FB-20AD4D02EF33}
  Size: 29.1 GB (31259639296 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
```

**Comment by pbatard** [comment] 2016-10-26 16:27
Looks like your ISO is corrupted. Can you extract `Sources/OEM/AfterImage.CMD` with [7-zip](http://www.7-zip.org/)?

**Comment by KohaviZ** [comment] 2016-10-26 16:36
yes i can (winrar but yes)

**Comment by pbatard** [comment] 2016-10-26 17:11
Then I'll need to have access to your ISO. Can you upload it somewhere?

**Comment by KohaviZ** [comment] 2016-10-26 17:12
where?

**Comment by pbatard** [comment] 2016-10-26 17:13
It's up to you. I think [mega.nz](https://mega.nz/) offers upload services. I'm afraid I don't have a dedicated server for uploads.

**Comment by KohaviZ** [comment] 2016-10-26 17:21
i am currently uploading to google drive. fine?

**Comment by pbatard** [comment] 2016-10-26 17:22
Yup, whatever suits you best. 
Also, if you don't want to share the download link with everybody, you can e-mail it to: pete@akeo.ie.

**Comment by KohaviZ** [comment] 2016-10-26 17:35
its taking for ever

**Comment by pbatard** [comment] 2016-10-28 08:29
Did you manage to upload your ISO anywhere? If so can you provide me with the link? Thanks.

**Comment by KohaviZ** [comment] 2016-10-28 15:52
Not yet... had issues with that...

**Comment by pbatard** [comment] 2016-10-28 17:00
No worries. Feel free to take your time and let me know when you've had a chance to do it.

**Comment by pbatard** [comment] 2016-10-30 18:19
Got your ISO now, and I'm afraid that, regardless of what happens with WinRAR, the problem __is__ that your ISO is either corrupted or was not mastered properly. Coz here's what happens when I try to extract the `Sources/OEM/AfterImage.CMD` with 7-zip:

![image1](https://cloud.githubusercontent.com/assets/1206968/19838718/5440bc7a-9ed5-11e6-8081-20dad4d6845a.png)

If both Rufus and 7-zip indicate that there is an issue with your ISO, and you confirmed that the ISO wasn't altered, then you will need to contact that company who created that ISO and tell them that they didn't master it properly (I would suggest that they test data extraction with 7-zip if they need proof).

Since there is nothing I can do if the ISO is problematic (I suspect that the WinRAR application is simply choosing to ignore errors rather than reporting them, which is not something I want to emulate in Rufus), I will now close this issue.

**Closed by pbatard** 2016-10-30 18:19 UTC
