### ISSUE TITLE
UEFI:NTFS "Could not locate '\efi\boot\bootx64.efi': [14] Not Found"

### ISSUE THREAD

**Issue by RufusUser** [pbatard/rufus#1299] opened 2019-04-10 13:44 UTC
This is my log if you need it
```
1 device found
Disk type: Removable, Disk size: 256 GB, Sector size: 512 bytes
Cylinders: 30448, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x001A3ECF
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 233.2 GB (250448163840 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2 (UEFI:NTFS):
  Type: EFI FAT (0xef)
  Size: 512 KB (524288 bytes)
  Start Sector: 489158618, Boot: No
Found USB 3.0 device 'SanDisk Ultra USB 3.0 USB Device' (0781:5591)
Using autorun.inf label for drive D: 'Little Big Usb'
1 device found
Disk type: Removable, Disk size: 256 GB, Sector size: 512 bytes
Cylinders: 30448, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 2
Disk ID: 0x001A3ECF
Drive has a Windows 7 Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 233.2 GB (250448163840 bytes)
  Start Sector: 2048, Boot: Yes
Partition 2 (UEFI:NTFS):
  Type: EFI FAT (0xef)
  Size: 512 KB (524288 bytes)
  Start Sector: 489158618, Boot: No
```
At least i think that's my log

**Comment by JonnyTech** [comment] 2019-04-10 13:48
The log does not state your reported message of `UEFI:NTFS "Could not locate '\efi\boot\bootx64.efi': [14] Not Found"`. Can you re-run then press the log button in Rufus (next to the start button) to grab a log with the fail.

**Comment by RufusUser** [comment] 2019-04-10 13:54
![image](https://user-images.githubusercontent.com/49486072/55884756-9ffdf500-5b76-11e9-93df-eed2d550d928.png)

**Comment by JonnyTech** [comment] 2019-04-10 14:10
Thanks but please include the full log of the disk creation from Rufus as that will show the files that were copied to the drive during its creation and any errors encountered.

**Comment by RufusUser** [comment] 2019-04-10 14:14
How?

**Comment by pbatard** [comment] 2019-04-10 14:19
@RufusUser, please don't ignore the check list. The log you provided __IS__ truncated,  which is explicitly mentioned you should not do in the check list.

You need to recreate your drive as you did before, and make sure you copy paste the __whole__ thing, starting with the line that has the Rufus version. Do not remove anything from your log and make sure you copy/paste the log after you re-created the drive in full.

It's only if you do that that we'll be able to help you.

**Comment by pbatard** [comment] 2019-04-10 14:23
Also, since the issue is most likely that the ISO you are trying to use does not have a `\efi\boot\bootx64.efi` file, are you absolutely sure that the ISO you are trying to boot is compatible with x64 UEFI systems? For instance, you cannot use a 32-bit Windows ISO and expect it to work with an x64 UEFI system (which is what you have).

**Comment by RufusUser** [comment] 2019-04-10 14:26
Ok i'll get a new iso and recreate then send you the log good?

**Comment by pbatard** [comment] 2019-04-10 14:31
You don't need to get a new ISO, unless you have found that the ISO you used was the wrong one (but in that case, and if you don't get the error from the title, you should just close the issue). You just need to re-do exactly what you did to create the USB that presented the problem, and provide the full log from Rufus then.

**Comment by RufusUser** [comment] 2019-04-10 14:36
Ok.  But my ISO is a x32 don't i need a x64 ISO?

**Comment by pbatard** [comment] 2019-04-10 14:38
Then that __IS__ your issue. You do need an x64 one, and if you use an x64 one then you will find that the error goes away.

I will therefore consider that this problem is resolved: Just get an x64 ISO. Your UEFI system is x64, you should not use a 32-bit ISO with it.

**Closed by pbatard** 2019-04-10 14:38 UTC

**Comment by RufusUser** [comment] 2019-04-10 14:41
What if it doesn't work do i still copy the log and send it to you?

**Comment by pbatard** [comment] 2019-04-10 14:42
If it doesn't work, then please open a new issue and make sure to follow the checklist (__DON'T__ remove it!!!), since the error you will get then will be different from the one above, and it will therefore be off-topic.

**Comment by RufusUser** [comment] 2019-04-10 15:02
Ok just to make sure i am tapping start this is my configuration

![image](https://user-images.githubusercontent.com/49486072/55890117-2539d780-5b80-11e9-81c4-676964727161.png)
