### ISSUE TITLE
Settings revert upon ISO image selection

### ISSUE THREAD

**Issue by frankgrimes69** [pbatard/rufus#573] opened 2015-08-14 14:55 UTC
(Using Rufus 2.2.668 on Windows 10 x64 with a USB 2.0 device and a Windows 8.1 x64 ISO file)

I tried to make a GPT UEFI bootable windows 8.1 USB flash drive but even after a couple of attempts I couldn't get my laptop to see the USB drive in UEFI mode. 

It turns out that when you select the ISO image (in my case the Windows 8.1 installation ISO) the settings for "file system" and "partition scheme" revert to other values which are incompatible with what I was trying to accomplish.

I suggest changing this behavior or moving the ISO selection setting above the settings it changes.

**Comment by pbatard** [comment] 2015-08-14 15:22
Duplicate of #117

**Closed by pbatard** 2015-08-14 15:22 UTC
