### ISSUE TITLE
Win2Go super slow after quick installation

### ISSUE THREAD

**Issue by Sunburst303** [pbatard/rufus#1752] opened 2021-06-19 09:02 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ x] Plugging the USB into a different port.
  - [ x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
I am installing Windows 10 Pro 21H1 via Rufus on a (Rufus recommended) SanDisk Extreme Pro 128GB for running on a Dell Latitude 5320 like a charm. First OOBE setup on the dell is working through even quite ok. Then when I first time normally boot Win10 from USB into login, until there it all goes fast as hell and as expected read write speeds at 30-100MB/s and then it goes installing some more Win updates and specifically drivers, suddenly the disk goes 100% with 5000-20000ms response, having like 300kb/s in read or write performance (I monitor it seems more the read part going hell low, sometimes going up into spikes like 10MB but right next dropping). I have been playing around with all different kind of HW changes even none dell PCs the stick won’t do any different. I even took an external USB connected SSD, again no difference.

That way windows on that usb is completely useless. What do I miss to check or update in Windows, drivers, Bios Settings (even though it took me days I installed latest drivers, bios etc. no change)? 

Any help highly appreciated! 

PS no logs as I find the Rufus install part is working all good (like 15-20 Minutes done - as expected). If you like to see more details just let me know which exactly.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment] 2021-06-19 12:29
> on a (Rufus recommended) SanDisk Extreme Pro 128GB

It's not because I sometimes used that drive for testing Windows To Go that I'd recommend it.

As a matter of fact I had just such one drive fail, for no apparent reason, while running Windows To Go on it, and I had to RMA it. I did not observe the slowdowns you saw though.

So, whereas it should be okay for the __occasional test__, the only configuration I can ever recommend for Windows To Go is a proper NVMe SSD in an USB 3.x <-> NVMe enclosure.

Please don't take my using this or that drive for testing as a recommendation. I am using whatever I have at hand.

> then it goes installing some more Win updates and specifically drivers, suddenly the disk goes 100% with 5000-20000ms response, having like 300kb/s in read or write performance

There again, please do not assume that Windows update installation is limited by disk speed. It is not! Windows does a lot of other things besides writing to disk during an update, and even writing to disk usually means overwrite rather than adding a new file, which is slow by definition.

>  I even took an external USB connected SSD, again no difference.

Then the issue is Windows or your hardware.

> Any help highly appreciated!

The only advice I can provide is to please post on a Windows forum. This is clearly not a Rufus issue, and there is no real help I can provide here except telling you to use a drive with the highest __random__ write speed you can find (typically an actual SSD) on the fastest connection you can have.

As such, I will close this issue.

**Closed by pbatard** 2021-06-19 12:29 UTC
