### ISSUE TITLE
legacy EFI layout feature. 

### ISSUE THREAD

**Issue by necrose99** [pbatard/rufus#1269] opened 2019-01-24 00:11 UTC
https://github.com/pbatard/rufus/issues/1125

screenshot is dead on..  any case need logs it works every time.. 
(had i newer equipment boots like from rufus 3.x like a charm.. , servers went down had to push images by hand to 20 or so boxes  **---just not my YE olden ASUS .)** 

(granted I find my self between gigs atm....else I've just get a 2019 laptop vs the 2011... ASUS ROG.. 
the EFI is flaky to say the least.  ) 

**at anyrate , I'd ask for the ability to use this layout as a feature.**  and if you get around to it. 
for old office systems etc.. 
however if I had 2018 and newer boxes  (i'd not care) 
worst case boot via bios ,  best case efi is working also ..  

for legacy hybrid mode , if I could  , just add the /root  /efistub @ end with rufus clone of ISO efi dir also..
clone boot sector for efi tuck in rufus efi's ..  else add the system reserved (akin to  BIOS GRUB in Linux ) stub to protect ye olden boot-loader.  as my system errors differently after trying but failing to load the uefi... 

bootstub ie reserved 5 megs   legacy boot bin bios hear. 
os loader 
efi fat32/fat16

while I can "Fail" to create media I have on UEFI/BIOS media.. with rufus older..  plain fat32... 
it will boot  , granted the wim needs editions craved off but doable.. 

(kick the wim to tmp , give it a major haircut.. ie **NTlite**.  while it fits and boots solve issue.. 
enable features ... via web /dism powershell etc. .... since we moved to a DSL only apt community this really sucks even more. unfortunately we needed the size , we just got boned on cable being in the area but not in our Units. 
as each feature was scrubed from your 1 edition while the 9 others got axed... , however can slpit the wim... pre-turning on features , then doping editions... ) 

(_do this to windows server iso's at your peril...  you'll get some irksome/interesting fails... re-baking iso's for STIG_. )

**Comment by pbatard** [comment] 2019-01-24 00:39
I have literally __no idea__ what you are asking here. Please reopen a proper feature request if you are asking for a new feature, indicating __precisely__ what problem you are trying to solve and, in case you think that Rufus is not creating a bootable drive as you want it, providing the full log of how you created the problematic drive.

Please remember: It's not because the problem is clear for you that it will be for others if you only provide fragments of information.

Closing issue as "No idea what is being asked here".

**Closed by pbatard** 2019-01-24 00:39 UTC
