### ISSUE TITLE
Add in Persian language

### ISSUE THREAD

**Issue by mahdigadi** [pbatard/rufus#534] opened 2015-06-19 07:59 UTC
Please,Create Persian language in the next Version of the program.
Thanks for your great software

**Comment by pbatard** [comment] 2015-06-19 09:09
Closing because this is a duplicate of #384.

The problem is: I don't speak Persian and nobody has volunteered to [create a Persian translation](https://github.com/pbatard/rufus/wiki/Translations-Status). As much as I would like to, this is not something I can add on my own.

**Closed by pbatard** 2015-06-19 09:09 UTC
