### ISSUE TITLE
[POSSIBLY] Error: [0xC0030090] The directory is not a subdirectory of the root directory.

### ISSUE THREAD

**Issue by incognito10278** [pbatard/rufus#1901] opened 2022-04-04 06:51 UTC
Thanks for the update, and the link to gifrecorder.

I tried some more with various drives, including drives that are larger than 500 GB as well as a 500 GB drive, but I never got your error.

I am therefore going to close this issue and wait to see if other people report something similar. If not, then it means it's probably something specific to your environment.

_Originally posted by @pbatard in https://github.com/pbatard/rufus/issues/1544#issuecomment-632687668_

**Comment by incognito10278** [comment] 2022-04-04 06:52
i also have the same error and cant seem to solve it

**Comment by pbatard** [comment] 2022-04-05 20:17
I need to see your log to determine if it's the same error.

I'm afraid I simply can't do anything from people reporting "me too!" on an issue I have never been able to replicate. You must provide data that might be able to help me reproduce the issue, but you haven't done that.

Without such data, and some hints from users like you as to what specific environmental parameters you have, compared to a standard Windows installation (since this issue only seems to occur to a very limited number of people), there can be no progress on this issue. 

At the very least, besides a log, which is __ALWAYS REQUIRED, EVEN IF YOU ARE FOLLOWING UP ON AN EXISTING ISSUE__, you should provide some clear information regarding the type of USB drive that was used including manufacturer, capacity and speed. Please remember that developers don't use crystal balls, so, even if it may sound harsh, the shortest way to get your issue remain unresolved, is to provide as little information as possible, such as discarding a __mandatory__ check list and just stating _"i also have the same error and cant seem to solve it"_.

**Comment by pbatard** [comment] 2022-04-09 01:15
With no new data to add the the previous issue, I have no choice but to close this duplicate.

**Closed by pbatard** 2022-04-09 01:15 UTC
