### ISSUE TITLE
Cannot detect USB

### ISSUE THREAD

**Issue by YoQiang** [pbatard/rufus#697] opened 2016-02-23 03:57 UTC
Cannot detect USB
```
Rufus version: 2.7.855
Windows version: Windows XP SP3 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Found USB device 'Kingston DT 101 G2 USB Device' (0951:1642) [GP]
Could not open '\\?\usbstor#disk&ven_kingston&prod_dt_101_g2&rev_pmap#001cc0ec34c9bb9187190211&0#{53f56307-b6bf-11d0-94f2-00a0c91efb8b}': [0x00000005] Access is denied.
A device was eliminated because it didn't report itself as a disk
0 devices found
```

**Comment by pbatard** [comment] 2016-02-23 10:05
This is a duplicate of #672, #639, #629... etc.

I all these cases `[0x00000005] Access is denied` means that __another__ application is preventing access to your drive (could be an antivirus, could be something else). Unfortunately, Windows makes it impossible for Rufus to tell what application that is (because there are no Windows APIs that can tell which applications are currently holding access to a __whole drive__), so you will have to figure out what it is.

Since there is nothing I can do in Rufus about other applications preventing access to USB drives, I will close this issue.

**Closed by pbatard** 2016-02-23 10:05 UTC
