### ISSUE TITLE
The option "Remove requirement for an online Microsoft account" does not appear

### ISSUE THREAD

**Issue by rizan9823** [pbatard/rufus#1958] opened 2022-06-26 04:35 UTC
﻿

Checklist
---------
- [ ] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<The option "Remove requirement for an online Microsoft account" doesn't appear in Rufus Beta version 3.19.1906, I tried it on Windows 11 straight away, didn't try on Windows 10>
![Cuplikan layar 2022-06-26 110712](https://user-images.githubusercontent.com/103547100/175799553-5b02e1c6-7981-45c3-a472-1786faf26a41.png)
![Cuplikan layar 2022-06-26 110744](https://user-images.githubusercontent.com/103547100/175799556-215de373-7e04-469e-a7a9-684a3df65865.png)

Log
---
```
<Rufus x86 v3.19.1906 (Beta)
Windows version: Windows 11 Pro, 64-bit (Build 22000.778)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
0 devices found>
```

**Comment by pbatard** [comment] 2022-06-26 07:59
Despite being explicitly asked to do so, you __truncated__ the log, which prevents me from obtaining the data I need to help you (your log should be one that shows what happens when you select an ISO, not one that you get by simply launching Rufus).

So, I'm just going to assume that you didn't read the [ChangeLog](https://github.com/pbatard/rufus/blob/master/ChangeLog.txt) that explicitly states _"allows to bypass the mandatory requirement for a Microsoft account on Windows 11 22H2"_ and are simply using the 22H1 version of Windows 11 where the bypass will not appear, __by design__, and therefore close this issue.

**Closed by pbatard** 2022-06-26 07:59 UTC

**Comment by pbatard** [comment] 2022-06-26 08:49
```
Detected: Windows 11 ISO (Build 22000.194)
```

Yup, 22000 is 22H1, so __BY DESIGN__, the option to bypass the forced account creation will not be proposed, because, unless you are using the Windows 11 __Home__ version, it's not needed (you just need to unplug your network and Windows Setup will allow you to create an offline account).

Please pay attention to the release notes before you submit an issue, because they explicitly state that the online account bypass is for Windows 11 22H2. Thank you.
