### ISSUE TITLE
when i choose the iso file ruffus closes directly

### ISSUE THREAD

**Issue by MoMahe** [pbatard/rufus#2278] opened 2023-07-10 10:18 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button (🗒️) or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, or used [DebugView](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview), and copy/pasted the log into the section that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
<Please describe your issue here>

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment] 2023-07-10 10:20
Most likely a duplicate of #2272. You are using a `_x86` version of Rufus and trying to open a Windows ISO, right?

**Comment by MoMahe** [comment] 2023-07-10 10:27
yeah

**Comment by pbatard** [comment] 2023-07-10 10:29
Then this will be fixed in the next release. In the meantime, you can install the Windows Store version from https://apps.microsoft.com/store/detail/9PC3H3V7Q9CH that doesn't suffer this problem.

Since this is a duplicate, I will close this issue.

**Closed by pbatard** 2023-07-10 10:29 UTC
