### ISSUE TITLE
Windows 10 (2004) create Win To Go fail - error at extract the ISO

### ISSUE THREAD

**Issue by ds2k5** [pbatard/rufus#1594] opened 2020-08-07 09:53 UTC
﻿
Tyed with: Rufus 3.11.1678 (Portable) and 3.10.1647 (Portable)
ISO: Win10_2004_German_x64.iso from: https://www.microsoft.com/de-de/software-download/windows10ISO
USB-Stick: 64GB ( had a working Win To Go 1909 on this Stick before )

Run the rufus.exe with local Admin rights.
Select the ISO
Select Windows To Go
Select Pro Version
Filesystem: NTFS
PartitonSchema: GPT
TargetSystem: UEFI (without CSM)

run until: ~23 % then fail with Error: Error at extract ISO

![2004](https://user-images.githubusercontent.com/11292286/89632668-d8b0fa00-d8a2-11ea-8777-2e1a4399de09.PNG)

How to fix this ?

HASH of the ISO is OK

![iso_hash](https://user-images.githubusercontent.com/11292286/89633184-bcfa2380-d8a3-11ea-96f2-e48de7d1e6c7.png)

![checked_iso_hash](https://user-images.githubusercontent.com/11292286/89633191-bff51400-d8a3-11ea-8901-529b82520c26.PNG)

**Comment by MG-96** [comment] 2020-08-09 15:35
Had the same Problem, I got these Log Messages in Rufus 3.11.1678:
```
[...]
Extracting: D:\sources\install.wim (4.2 GB)
Write error [0x00000015] The device is not ready.
Retrying in 5 seconds...
Write error [0x00000015] The device is not ready.
Retrying in 5 seconds...
``` 
Also I used the `Win10_2004_German_x64.iso` .

However it worked with no problems on the second try...
Hope this helps if people keep getting this and if further investigation will be done.

**Comment by pbatard** [comment] 2020-08-09 15:41
@MG-96, if you get a `The device is not ready` in the middle of extraction, then this is clearly an issue that has nothing to do with Rufus. It means that either your USB Flash Drive has an issue or some external application (e.g. security solution) is interfering with the copy process.

@ds2k5, you **chose** not to follow the check list and not provide a log (which is further confirmed by the fact that you computed your SHA using an external application, whereas the check list tells you exactly how to do that in Rufus.

As such, and as indicated in the check list, I will close this issue, as I can't help people who choose not to follow the check list and I am missing the data I need to investigate.

The check list is __NOT__ optional.

**Closed by pbatard** 2020-08-09 15:41 UTC

**Comment by sk7** [comment] 2021-03-07 18:43
I had a similar error and the reason was that I was opening the ISO image from a network drive (Windows was in Parallels VM and i had the file on the host system). Copying the ISO image to a local file system fixed this for me.
