### ISSUE TITLE
Rufus 1.4.12 crash

### ISSUE THREAD

**Issue by azdps** [pbatard/rufus#429] opened 2015-01-11 23:58 UTC
Rufus crash using 1.4.12

I'm running Windows 7 x64

How to reproduce crash:
- do not have a flash drive in usb port (rufus should open with the device combobox showing empty)
- start rufus
- select either MS-DOS, FreeDOS, DD Image, ISO Image or DD Image from drop down box
- click on "select and image button"
- select "all files" from the drop down list
- select a file other than a valid image file such as a text file
- rufus crashes

**Comment by pbatard** [comment] 2015-01-12 00:03
Duplicate of #405, which was fixed with c56d1a054541f46a48053be82e7280ac33687be6.
Please test with Rufus 2.0 ALPHA, available [here](https://rufus.akeo.ie/test/) and reopen this issue if you find the problem is still present.

**Closed by pbatard** 2015-01-12 00:03 UTC
