### ISSUE TITLE
Non Bootable on MacMini 2018 (Intel)

### ISSUE THREAD

**Issue by startergo** [pbatard/rufus#1923] opened 2022-05-05 13:35 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [ ] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
Does not boot Windows 10 USB on Mac Mini 2018. Most probably due to signing, which is not accepted by Apple. It goes straight to Apple recovery.

Log
---
```
<FULL LOG>
```

**Comment by pbatard** [comment] 2022-05-05 17:15
As much as I'd like to help, this is an issue that exist purely between Mac hardware and Windows software.

Windows create bootable media that follow the current UEFI specs and uses bootloaders that are signed by Microsoft themselves.

So, if that doesn't work, you need to take this either to Apple or Microsoft, as Rufus did create a UEFI compliant boot media, and if the problem is that Apple has decided that they were "above" following boot specifications that everybody else in the world uses, then you need to make your voice heard to Apple.

&rarr; Closing

**Closed** 2022-05-10 10:01 UTC
