### ISSUE TITLE
Please add support to seagate firmware ISOs

### ISSUE THREAD

**Issue by lunter2** [pbatard/rufus#473] opened 2015-03-21 17:01 UTC
Please add support to seagate firmware ISOs

http://www.seagate.com/staticfiles/support/downloads/firmware/Barracuda12-ALL-CC49.iso

**Comment by pbatard** [comment] 2015-03-21 17:09
This is a duplicate of #63 (which, to be honest, I have no idea when/if will ever be implemented).

For now, please have a look at [this](https://github.com/pbatard/rufus/wiki/FAQ#Im_trying_to_work_with_an_ISO_but_Rufus_says_its_unsupported). You're basically trying to run DOS tools, so you should use FreeDOS and then extract the relevant content from the ISO onto your USB.

Closed as duplicate.

**Closed by pbatard** 2015-03-21 17:09 UTC
