### ISSUE TITLE
Can't create a Windows 10 bootable USB driver

### ISSUE THREAD

**Issue by djanthony93** [pbatard/rufus#819] opened 2016-08-28 17:40 UTC
Hello, I' m trying to create an USB driver with a Windows 10 ISO image, here is my error log:
```
Rufus version: 2.10.973
Windows version: Windows 10 64-bit (Build 14393)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta3
System locale ID: 0x0410
Will use default UI locale 0x0410
Found USB 3.0 device 'SanDisk Ultra Fit USB Device' (0781:5583)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3781, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 29.0 GB (31104958464 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'W10MulAgoAtt64'
  Size: 4447436800 bytes
  Uses: EFI
  Uses: Bootmgr
  Uses: Install.wim (version 0.13.1)
Using image: W10MulAgoAtt64.iso

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE2 for write access
Will use 'E:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has an unknown Master Boot Record
Volume has an unknown Partition Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 0 sectors
Deleting partitions...
Partitioning (MBR)...
Could not set drive layout: [0x00000032] Richiesta non supportata.
Re-mounted volume as 'E:' after error

Found USB 3.0 device 'SanDisk Ultra Fit USB Device' (0781:5583)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 3781, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000001
Drive has an unknown Master Boot Record
Partition 1:
  Type: Small FAT16 (0x04)
  Size: 29.0 GB (31104958464 bytes)
  Start Sector: 0, Boot: No, Recognized: Yes
Saved D:\Antonio\Downloads\rufus\rufus.log
```

**Comment by pbatard** [comment] 2016-08-28 21:32
Duplicate of #814 (next time, please follow the checklist, which specifically asks you to look for existing similar issues). You can try the workaround mentioned in #814 ( try <kbd>Alt</kbd>-<kbd>Z</kbd> in Rufus, to zero the drive, then cancel it after a while, and try reformatting your drive again) or try [this preview version of Rufus 2.11](https://rufus.akeo.ie/testing/rufus-2.11_TEST2.exe).

**Closed by pbatard** 2016-08-28 21:32 UTC
