### ISSUE TITLE
Downloading the file "syslinux.6.04" creates the folders but does not download anything

### ISSUE THREAD

**Issue by idkrick1** [pbatard/rufus#1276] opened 2019-03-05 13:33 UTC
![insulesess](https://user-images.githubusercontent.com/48229530/53808495-c225a700-3f28-11e9-911b-430aa9b9e5ce.png)

**Log**
Rufus x86 v3.4.1430
Windows version: Windows 7 SP1 32 bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0C0A
Will use default UI locale 0x0C0A
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'es-ES'
Found USB 2.0 device 'Generic Flash Disk USB Device' (1E3D:2096)
1 device found
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 489, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0002A5FE
Drive has a Rufus Master Boot Record
Partition 1:
  Type: FAT32 (0x0b)
  Size: 3.8 GB (4026531840 bytes)
  Start Sector: 2048, Boot: Yes
Found USB 2.0 device 'Generic Flash Disk USB Device' (1E3D:2096)
1 device found
Disk type: Removable, Disk size: 4GB, Sector size: 512 bytes
Cylinders: 489, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0002A5FE
Drive has a Rufus Master Boot Record
Partition 1:
  Type: FAT32 (0x0b)
  Size: 3.8 GB (4026531840 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20181203 (from '/isolinux/isolinux.bin')
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Kali Live'
  Size: 3.3 GB (Projected)
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.04
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system limitations.
  Because of this, some features from this image may not work...
Using image: kali-linux-2019.1-i386.iso (3.3 GB)
Downloading https://rufus.ie/files/syslinux-6.04/20181203/ldlinux.sys
Unable to send request: This system's SSL library is too old to be able to access this website.
Extended version was not found, trying main version...
Downloading https://rufus.ie/files/syslinux-6.04/ldlinux.sys
Unable to send request: This system's SSL library is too old to be able to access this website.
Could not download the file - cancelling

[https://rufus.ie/files/syslinux-6.04/20181203/ldlinux.sys](url)
Not Found 404

[ https://rufus.ie/files/syslinux-6.04/ldlinux.sys](url)

It works, but when you put the file, nothing happens

**Comment by pbatard** [comment] 2019-03-05 13:48
Next time, please follow the check list and perform a search for the error message you have:
```
Unable to send request: This system's SSL library is too old to be able to access this website.
```
If you had done that, you would have seen that your issue was a duplicate of #1232, and that you will find how you should proceed to fix it.

Closing as: _duplicate of existing issue_.

**Closed by pbatard** 2019-03-05 13:48 UTC
