### ISSUE TITLE
Linux iso not OK!

### ISSUE THREAD

**Issue by kris0725pl** [pbatard/rufus#2307] opened 2023-08-19 20:25 UTC
pop-os_22.04_amd64_intel_33.iso

I cant create proper iso on pendrive...i got information somethigs like DD 
On windows 10 iso i got always blue screen and not working. 

Rufus...very bad app :(

**Comment by pbatard** [comment] 2023-08-19 22:32
Well, you're the only person reporting such behaviour (you can search this issue tracker and you will see that nobody else is reporting BSODs from using Rufus to create media), so I'm afraid that if you do experience a blue screen when writing the latest PopOS! ISO, then the issue is with your environment.

Below is my report from using Rufus 4.2 with `pop-os_22.04_amd64_intel_33.iso` which worked just fine.

```
Rufus x64 v4.2.2074
Windows version: Windows 11 Pro for Workstations x64 (Build 22621.2134)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.06
System locale ID: 0x0809 (en-GB)
Will use default UI locale 0x0809
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found 517 officially revoked UEFI bootloaders from embedded list
Found 2351 additional revoked UEFI bootloaders from this system's SKUSiPolicy.p7b
Found USB device 'Mushkin Ventura Ultra USB Device' (174C:55AA) [ID]
Using 'autorun.inf' label for drive F: 'ARCH_202308'
1 device found
Disk type: FIXED, Disk size: 120 GB, Sector size: 512 bytes
Cylinders: 14593, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00E6F936
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Detected File System: FAT32
  Size: 111.8 GB (120033050624 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Detected Syslinux version: 6.04/20191223 (from '/isolinux/isolinux.bin')
  Reported Grub version: 2.04
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Pop_OS 22.04 amd64 Intel'
  Size: 2.5 GB (Projected)
  Has a >64 chars filename
  Uses: Syslinux/Isolinux v6.04
  Uses: GRUB2 (2.04)
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system
  limitations. Because of this, some features from this image may not work...
Note: DD image mode enforced since this ISOHybrid is not ISO mode compatible.
Using image: pop-os_22.04_amd64_intel_33.iso (2.5 GB)

Format operation started
Requesting disk access...
Will use 'F:' as volume mountpoint
Opened \\.\PhysicalDrive9 for exclusive write access
Requesting logical volume handle...
No logical drive found (unpartitioned?)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Opened \\.\PhysicalDrive9 for shared write access

Found USB device 'Mushkin Ventura Ultra USB Device' (174C:55AA) [ID]
No logical drive found (unpartitioned?)
1 device found
No volume information for drive 0x89
Disk type: FIXED, Disk size: 120 GB, Sector size: 512 bytes
Cylinders: 14593, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x31D1B347
Drive has an unknown Master Boot Record
Partition 2:
  Type: EFI System Partition (0xef)
  Detected File System: FAT12
  Size: 4 MB (4194304 bytes)
  Start Sector: 488, Boot: No
Found USB device 'Mushkin Ventura Ultra USB Device' (174C:55AA) [ID]
No logical drive found (unpartitioned?)
1 device found
No volume information for drive 0x89
Disk type: FIXED, Disk size: 120 GB, Sector size: 512 bytes
Cylinders: 14593, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x31D1B347
Drive has an unknown Master Boot Record
Partition 2:
  Type: EFI System Partition (0xef)
  Detected File System: FAT12
  Size: 4 MB (4194304 bytes)
  Start Sector: 488, Boot: No
```

Oh and before you complain about the fact that I tested on Windows 11 and not Windows 10 (I'm afraid I don't have access to a Windows 10 machine atm), please bear in mind that if the issue is really that Windows 10 BSODs whereas Windows 11 doesn't (which is exceedingly doubtful) then the logical take away would be that Microsoft discovered a bug in Windows 10 that they did fix in Windows 11, and that the issue is unrelated to using Rufus.

But again, considering that quite a few people do use Rufus to create PopOS! media on Windows 10, and that they don't seem to report an issue similar to yours, I can only dismiss your problem as a purely environmental issue and as a result, I will close it.

**Closed by pbatard** 2023-08-19 22:32 UTC
