### ISSUE TITLE
Disk freezes explorer, crashes most programs that attempt to access it

### ISSUE THREAD

**Issue by b0rah** [pbatard/rufus#1658] opened 2020-12-01 05:18 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [x] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [x] I also tried one or more of the following:
  - [x] Using a different USB drive.
  - [x] Plugging the USB into a different port.
  - [x] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

To be more clear:
Rufus, when cancelling the USB flash process in the middle of it, has left a drive reading only 0s and will not show up in File Explorer. I would have only opened an issue if I didn't know of any other solution-I have checked online and most of the suggested solutions to anything similar fail. Chkdsk says that there is no media, anything format-related failed, some say the disk is too large, or too small, and I am at a total loss of what to do to hopefully get the disk working. There's no data on it, and as such I'm more concerned about how this happened and possible fixes. I have tried formatting it on other devices with the same result, Explorer crashes and formatting it fails. I have also tried Rufus on other devices with the same lack of success (alt-f did not help.) It fails with "Error formatting drive" and throws error 0x00000015. One of the few programs I tried that managed to access the disk reported that the time to wipe it would be 999999999 minutes, which seems a little off. I'm no expert on these matters and I am genuinely puzzled as to the cause of the issue. 

Log
---
```
Rufus x86 v3.13.1730 (Portable)
Windows version: Windows 10 64-bit (Build 19041.630)
Syslinux versions: 4.07/2013-07-25, 6.04/pre1
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0409 (en-US)
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 
Localization set to 'en-US'
0 devices found
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Drive does not have a Boot Marker
Found USB 3.0 device 'Netac OnlyDisk USB Device' (0DD8:3200)
1 device found
No volume information for drive 0x81
Disk type: Removable, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15170, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 0
Disk ID: 0x00000000
read_sectors: Read error [0x00000015] The device is not ready.
  Read: 0, Expected: 512
  StartSector: 0x00000000, nSectors: 0x1, SectorSize: 0x200
Device does not have a Boot Marker
0 devices found
0 devices found
```

**Comment by pbatard** [comment] 2020-12-01 13:33
> Rufus has managed to corrupt 2 USB sticks with NORMAL USE. I had to cancel the installation of a Linux Mint bootable USB (...)

This is not normal use. If you have to cancel, then it means that either Rufus already detected that your USB was defective, and therefore was having trouble writing to it, or, if you decided to cancel at random whereas the write operation seemed to be fine, then you accepted the large warning displayed by Rufus that cancellation may leave the drive UNUSABLE (not because Rufus might be doing something wrong, but because we can't vouch for how some poorly designed flash drive controllers might react on Windows cancelling a write operation, which is really the one reason the warning is there). So, in either case, I don't see much of anything normal with regards to your usage.

> I'd at least like an explanation as to why this happened

There can be many reasons, but I'm afraid that, as much as you might like to be able to point the finger at Rufus being the cause of your problem, none have to do with Rufus being somehow able to corrupt a flash drive. That is [just not how things work](https://github.com/pbatard/rufus/wiki/FAQ#Help_Rufus_damaged_my_flash_drive). Unless Windows has a major bug, and/or your flash drives are poorly designed (because it would really take one but most likely two of these things to __consistently__ damage a flash drive), an application like Rufus simply does not have the capability to render a flash drive inoperable. The reason for that is that, unlike what people think, Rufus is not building custom USB commands that it sends on the USB bus, that could get corrupted and lead to trouble. Instead, the only thing it ever does when writing an image is either ask Windows:
- Write this block of data, to this **ABSTRACTED** disk here
- Write this file to this **ABSTRACTED** volume here

That's all. And yes the **ABSTRACTED** is important, because, as far as Rufus is concerned, the disk can be anything and there's NO DIFFERENCE WHATSOEVER between a USB drive, a Virtual drive, a SATA HDD or NVMe SSD. Windows abstracts these all the same, and, outside of enumeration (which doesn't ever write anything to the drives) we are only ever using these abstracted devices, which we don't actually need to know or care the exact nature of.

And since there are NO "special" blocks on an abstracted disk device that decide whether a disk works or not, you could take the most buggy application you want, and write complete garbage to a USB flash drive all day, and still not be able to damage the drive in the slightest (outside of the standard wear and tear, but that's not something that comes into play here).

So, while I understand that you may think that, because you encountered a hardware failure when Rufus while writing to your drive, you may be tempted to think that Rufus must have damaged the drive, I'm afraid that this is just not how it works or even **can** work. Your hardware failed for one reason or another and as a **consequence** Rufus experienced a write issue, which it either reported or which led you to cancel the operation.

As to possible explanations, well the first thing to check for would be fake drives, that seem to work beautifully until the day you write just a bit too much data on them (typical of what you'd do when writing an ISO image), and then don't work at all. Or you could have flaky USB power supply or temperature issues, which your flash drives don't like too much, and which would be exacerbated when a sustained amount of data is being written. Or it could be your EM environment. Or flaky cables. Or the myriad of external elements that may cause a flash drive to fail. And let's also not forget that the flash memory use in USB flash drives is a lot less reliable than people realize. 

For instance, I recently had to RMA a relatively recent 128GB SanDisk Extreme Pro USB 3.1, which I was using on a Pi 4 to run Windows ARM64 (in a kind of Windows To Go mode, but I didn't even use Rufus to create that drive), and which I had left sitting on a shelf for about a couple of weeks. I had actually __not__ been using that drive with Rufus at all, since it was dedicated for that Windows installation, and it just stopped being recognized from one day to the next, even as it was a relatively high end product from a very reputable brand (and it was really a case of works one day, unplug it and leave it on a shelf for some days, doesn't work). And the kicker is that, even after 8 years of development and constant testing, the only flash drive failures I have ever experienced have all been outside of any Rufus usage. Especially, so far, I have NEVER had a drive failure while using Rufus (which I am actually the first to be surprised about because, due to my usage and the amount of testing I need to conduct as part of development, as well as my less than gentle treatment of the flash drives I use for testing, I should statistically have experienced some failures, even more so as most of the drives I use are now more than 5 years old).
 
So, yes, flash based media will fail, and you don't have to try to point the finger at an application to explain these failures, as you will find the same problems being reported by users of any similar applications (for instance, you'll get similar threads for users who are convinced that balenaEtcher killed their flash drives even as, just like Rufus, it simply does not have this "capability").

Since there's really nothing more I can do when it comes to hardware failures (there do exist some weird Windows bugs that may make a drive look unusable, but these shouldn't manifest themselves when writing a Linux Mint image. Still, you may want to try to recover your drive on Linux just in case), I'm just going to close this issue.

**Closed by pbatard** 2020-12-01 13:33 UTC
