### ISSUE TITLE
Zero Drive Functionality cannot be disabled once triggrered

### ISSUE THREAD

**Issue by deadair3210** [pbatard/rufus#651] opened 2015-12-11 22:36 UTC
Version = 2.6.816 Beta
If the Zero Drive cheat mode (<kbd>Alt</kbd>-<kbd>Z</kbd>) is enabled any time in a runtime of the program, the mode cannot be disabled unless the program is restarted

Procedure
1 - Enable <kbd>Alt</kbd>-<kbd>Z</kbd>
2 - Hit cancel
3 - Even though the user hit cancel, and possibly changed options in the program, once start is pressed the program will begin Zeroing the drive

EDIT = I was mistaken on a part, the feature will disable correctly if the user hits stop after the program starts zeroing the drive. The problem is that the program will zero the drive wether the user hits ok pr cancel. Ok causes the program to start zeroing the drive, and cancel causes the program to start zeroing the drive after start is pushed no matter if other options are changed after the dialog was canceled

**Comment by pbatard** [comment] 2015-12-11 23:06
Thanks for the report.

I'd like to fix the problem, but I'm afraid, even with the added explanation, I still can't reproduce it. I don't think I quite understand the exact steps that are needed to see the issue. Can you please tell exactly which controls one needs to press, from a clean start of Rufus, to see the issue?

**Comment by pbatard** [comment] 2015-12-11 23:08
Ah, I get you know - you need to press 'Cancel' on the first prompt after <kbd>Alt</kbd>-<kbd>Z</kbd>. Let me fix that.

**Comment by pbatard** [comment] 2015-12-11 23:22
This should be fixed now. I don't think I want to publish a new BETA, but I did put a TEST version with the fix that will go into 2.6 release [here](https://rufus.akeo.ie/testing/). I will close this issue, but don't hesitate to let me know if you still see issues related to zeroing drives in the new TEST version.

Many thanks again for testing the BETA and spotting this issue!

**Closed** 2015-12-11 23:23 UTC
