### ISSUE TITLE
ISO extraction failure

### ISSUE THREAD

**Issue by george2781** [pbatard/rufus#1195] opened 2018-08-14 10:46 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [ ] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.
- [ ] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [x] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------

Cannot use Rufus to create a bootable usb with

Log
---

```
Rufus version: 3.1.1320
Windows version: Windows 10 32 bit (Build 14393)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02
System locale ID: 0x0409
Will use default UI locale 0x0409
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found card reader device 'Samsung BGND3R'
Found USB 2.0 device 'Generic Flash Disk USB Device' (058F:6387)
1 device found
Disk type: Removable, Disk size: 32GB, Sector size: 512 bytes
Cylinders: 3824, Tracks per cylinder: 255, Sectors per track: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x057CC97D
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 29.3 GB (31456231424 bytes)
  Start Sector: 2048, Boot: Yes
Scanning image...
ISO analysis:
  Image is an ISO9660 image
  Will use '/isolinux/isolinux.cfg' for Syslinux
  Error reading ISO9660 file /isolinux/isolinux.bin at LSN 932694
  Could not access /isolinux/isolinux.bin
  Warning: Could not detect Isolinux version - Forcing to 6.03 (embedded)
Disk image analysis:
  Image has an unknown Master Boot Record
  Image is a bootable disk image
ISO label: 'Ubuntu 18.04.1 LTS amd64'
  Size: 1.8 GB (Projected)
  ERROR: Detected that file on disk has been truncated by 1.2 GB!
  Uses: Syslinux/Isolinux v6.03
  Uses: EFI
  Note: This ISO uses symbolic links, which will not be replicated due to file system limitations.
  Because of this, some features from this image may not work...
Using image: ubuntu-18.04.1-desktop-amd64.iso (661.6 MB)

Computing checksum for 'C:\Users\georg\Desktop\ubuntu-18.04.1-desktop-amd64.iso'...
  MD5:	 4ecf849469b7daf5acebfd5b4931715b
  SHA1:	 999f0c8a30bd34eca1ff094d841ffd08a79b78d6
  SHA256: 1ec698b4a55c6d8e74f171a01b5e5d6530276f45f5ef96bd8857445bba0cd688
Will reuse 'ldlinux.sys' and 'ldlinux.bss' from './rufus_files/rufus_files/syslinux-6.03/' for Syslinux installation

Format operation started
Requesting disk access...
Opened \\.\PHYSICALDRIVE1 for exclusive write access
Requesting lock...
```

**Comment by pbatard** [comment] 2018-08-14 10:55
> - [x] I clicked the "Log" button in Rufus (last small blue button before _START_) and copy/pasted the log into the line that says `<FULL LOG>` below.

If you really did that, then there should be a log. Please provide the full log, or I will have to close this issue.

**Comment by george2781** [comment] 2018-08-14 10:55
trying yet can't get log

**Comment by pbatard** [comment] 2018-08-14 10:58
Do you have an issue accessing the log in Rufus? Or do you have an issue copy/pasting the log into the github issue tracker?

As explained in the steps, you just need to click the last small button before _START_ to get the log window to display in Rufus, and once you have it you can click _Save_ to save the log to a file.

Then, if github doesn't let you copy/paste the content of the file, you can always attach it to the issue by dragging and dropping the file.

**Comment by george2781** [comment] 2018-08-14 10:59
accessing the log

**Comment by pbatard** [comment] 2018-08-14 11:01
![image1](https://user-images.githubusercontent.com/1206968/44088091-c8f3814c-9fb9-11e8-8ad8-a225660c25f2.png)

**Comment by george2781** [comment] 2018-08-14 11:02
ok got it thank you

**Comment by george2781** [comment] 2018-08-14 11:03
might take a minute

**Comment by pbatard** [comment] 2018-08-14 11:03
No worries. Take your time.

**Comment by george2781** [comment] 2018-08-14 11:05
ok got it

**Comment by pbatard** [comment] 2018-08-14 11:07
So the issue is that Rufus appears to freeze after the `Requesting lock...` message?

I thought the issue was a file extraction failure (which would produce a different message in the log).

Are you sure you copy/pasted the whole log?

**Comment by george2781** [comment] 2018-08-14 11:08
yes

**Comment by george2781** [comment] 2018-08-14 11:11
![capture](https://user-images.githubusercontent.com/42376099/44088510-3cf3e356-9fbb-11e8-8d13-f3e01a3afb44.JPG)

**Comment by pbatard** [comment] 2018-08-14 11:12
Also, looking further at the log, I think your issue is pretty obvious:

```
ERROR: Detected that file on disk has been truncated by 1.2 GB!
```

Means that your download is __corrupt__.

Also, the SHA-256 you got does not match with the official SHA-256 for Ubuntu 18.04.1. You got `1ec698b4a55c6d8e74f171a01b5e5d6530276f45f5ef96bd8857445bba0cd688`, whereas the correct one is `5748706937539418ee5707bd538c4f5eabae485d17aa49fb13ce2c9b70532433`.

Corrupt download. You'll need to sort that out on your own, as it has nothing to do with Rufus.

Next time, please pay a bit more attention to the checklist, especially the part that says, about the checksum:

> I confirmed, by performing an internet search, that these values match the ones from the official image.

**Comment by pbatard** [comment] 2018-08-14 11:13
For what is worth, you can find the proper checksums [here](http://releases.ubuntu.com/18.04/SHA256SUMS)

**Closed by pbatard** 2018-08-14 11:12 UTC
