### ISSUE TITLE
Cannot create new bootable usb Unable to create file: [0x00000002]

### ISSUE THREAD

**Issue by Dmanisaround** [pbatard/rufus#494] opened 2015-04-23 21:36 UTC
I'm using Rufus 2.1.649 and trying to create a bootable usb with an Adata uv128 /16 usb 3.0 drive. Windows 8.1

The process goes along normally until at the same point every time the usb port dies and losses the usb drive and the usb drive is completely disconnected. Here is the log. Note that it crashes on the same file every time Extracting: D:\lsu_lsi_.v00 (78 KB). Note that this does not happen when I format any of my usb 2.0 flash drives using the same iso.

```
Rufus version: 2.1.649
Windows version: Windows 8.1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Found USB device 'SDHC Card' (????:????)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15927345152 bytes)
  Start Sector: 8192, Boot: No, Recognized: Yes
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15927345152 bytes)
  Start Sector: 8192, Boot: No, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
1 device found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15927345152 bytes)
  Start Sector: 8192, Boot: No, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15927345152 bytes)
  Start Sector: 8192, Boot: No, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00000000
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15927345152 bytes)
  Start Sector: 8192, Boot: No, Recognized: Yes
Scanning image...
Disc image is an ISO9660 image
Will use /isolinux.cfg for Syslinux
Detected Isolinux version: 3.86 (from '/isolinux.bin')
ISO label: ESXI-6.0.0-2494585-STANDARD
  Size: 365021184 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: No
  Uses EFI: Yes
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: Yes (3.86)
    With an old menu.c32: Yes
    With an old vesamenu.c32: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
Using image: VMware-VMvisor-Installer-6.0.0-2494585.x86_64.iso
Will replace obsolete 'menu.c32' from ISO with the one found in './rufus_files/syslinux-4.07/menu.c32'

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE1 for write access
Will use 'E:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 8192 bytes
Quick format was selected
Creating file system...
Cancelling
Format error: Cancelled by user.
Re-mounted volume as 'E:' after error

Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01062C07
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15930490880 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01062C07
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15930490880 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Closed Windows format prompt
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
No volume information for drive 0x81
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01062C07
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15930490880 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01062C07
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15930490880 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Found USB device 'SDHC Card' (????:????)
Found USB 3.0 device 'ADATA USB Flash Drive USB Device' (125F:DB8A)
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1936, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x01062C07
Drive has a Zeroed Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.8 GB (15930490880 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
2 devices found
Disk type: Removable, Sector Size: 512 bytes
Cylinders: 1886, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x0101A15E
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 14.5 GB (15517876224 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Scanning image...
Disc image is an ISO9660 image
Will use /isolinux.cfg for Syslinux
Detected Isolinux version: 3.86 (from '/isolinux.bin')
ISO label: ESXI-6.0.0-2494585-STANDARD
  Size: 365021184 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: No
  Uses EFI: Yes
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: Yes (3.86)
    With an old menu.c32: Yes
    With an old vesamenu.c32: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
Using image: VMware-VMvisor-Installer-6.0.0-2494585.x86_64.iso
Will replace obsolete 'menu.c32' from ISO with the one found in './rufus_files/syslinux-4.07/menu.c32'

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE2 for write access
Will use 'D:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Syslinux Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Formatting (FAT32)...
Using cluster size: 8192 bytes
Quick format was selected
Creating file system...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume GUID \\?\Volume{837b812c-e9fc-11e4-bf2f-28187837d16a}\
Installing Syslinux 3.86...
Successfully wrote 'ldlinux.sys'
Opened drive \\?\Volume{837b812c-e9fc-11e4-bf2f-28187837d16a} for write access
Successfully wrote Syslinux boot record
Successfully remounted Volume{837b812c-e9fc-11e4-bf2f-28187837d16a}\ on D:\
Copying ISO files...
Extracting files...
Disc image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: D:\.discinfo (32 bytes)
Extracting: D:\a.b00 (11.0 KB)
Extracting: D:\ata_pata.v00 (8.3 KB)
Extracting: D:\ata_pata.v01 (6.2 KB)
Extracting: D:\ata_pata.v02 (6.5 KB)
Extracting: D:\ata_pata.v03 (7.2 KB)
Extracting: D:\ata_pata.v04 (8.3 KB)
Extracting: D:\ata_pata.v05 (7 KB)
Extracting: D:\ata_pata.v06 (6.2 KB)
Extracting: D:\ata_pata.v07 (7.6 KB)
Extracting: D:\b.b00 (74.4 KB)
Extracting: D:\block_cc.v00 (23.8 KB)
Extracting: D:\boot.cat (512 bytes)
Extracting: D:\boot.cfg (1.6 KB)
Extracting: D:\chardevs.b00 (18.6 KB)
Extracting: D:\efi\boot\boot.cfg (1.6 KB)
Extracting: D:\efi\boot\bootia32.efi (94.2 KB)
Extracting: D:\efi\boot\bootx64.efi (96.3 KB)
Extracting: D:\efiboot.img (1 MB)
Extracting: D:\ehci_ehc.v00 (33.3 KB)
Extracting: D:\elxnet.v00 (118 KB)
Extracting: D:\emulex_e.v00 (5.7 KB)
Extracting: D:\esx_dvfi.v00 (89.2 KB)
Extracting: D:\ima_qla4.v00 (359.4 KB)
Extracting: D:\imgdb.tgz (40.4 KB)
Extracting: D:\imgpayld.tgz (3.9 MB)
Extracting: D:\ipmi_ipm.v00 (9.4 KB)
Extracting: D:\ipmi_ipm.v01 (23.0 KB)
Extracting: D:\ipmi_ipm.v02 (27.9 KB)
Extracting: D:\isolinux.bin (14 KB)
Extracting: D:\isolinux.cfg (267 bytes)
Extracting: D:\jumpstrt.gz (20 bytes)
Extracting: D:\k.b00 (3.2 MB)
Extracting: D:\lpfc.v00 (492.5 KB)
Extracting: D:\lsi_mr3.v00 (68.8 KB)
Extracting: D:\lsi_msgp.v00 (118.0 KB)
Extracting: D:\lsu_hp_h.v00 (15.3 KB)
Extracting: D:\lsu_lsi_.v00 (78 KB)
  Unable to create file: [0x00000002] The system cannot find the file specified.
Unable to create D:\syslinux.cfg - booting from USB will not work
```

**Comment by pbatard** [comment] 2015-04-23 22:23
> Note that this does not happen when I format any of my usb 2.0 flash drives using the same iso

The problem is clearly with your hardware, not Rufus.
If you plug your Adata device to an USB 2.0 port (or use an USB 2.0 extension cable), you will most likely find that it works just fine, which indicates that your issue is with high speed interferences, which can be due to poor cabling (are you using an USB 3.0 extension cable by any chance?) or poor controller isolation.

Rufus is usually much faster than other tools, so it tends to exacerbate these kind of hardware issues. Short of forcefully trying to slow down transfers, which is not something I want to do because I don't think people who can run properly at USB 3.0 speeds should be penalized by people using subpar hardware, this is not something that can be addressed in Rufus...

Please try on another computer that supports USB 3.0, and see what happens. Also it might help to check the SHA1 of your ISO just in case (though the fact that it works with an USB 2.0 device indicates that this is probably not a corrupted ISO issue).

For the record, I have had no issue using `VMware-VMvisor-Installer-6.0.0-2494585.x86_64.iso` (SHA1: `a38a9d37ea529329338de049679c1dd1687d3860`) with the fastest USB 3.0 device I have (Mushkin Ventura Ultra), even as I was using an USB 3.0 extension cable (The fact that it's [UAS](http://en.wikipedia.org/wiki/USB_Attached_SCSI) rather than USB shouldn't matter, as Rufus doesn't do anything different, and I also tried with a slightly slower but non UAS USB 3.0 device, with the same successful outcome):

```
Rufus version: 2.2.651
Windows version: Windows 8.1 64-bit
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.02~beta2
Locale ID: 0x0409
Found UAS (USB 3.0) device 'Mushkin Ventura Ultra SCSI Disk Device' (174C:55AA)
1 device found
Disk type: Fixed, Sector Size: 512 bytes
Cylinders: 14593, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x000B8B04
Drive has a Rufus Master Boot Record
Partition 1:
  Type: NTFS (0x07)
  Size: 111.8 GB (120033075200 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
Scanning image...
Disc image is an ISO9660 image
Will use '/isolinux.cfg' for Syslinux
Local time: 13074300996
Checking for Rufus updates...
Checking release channel...
Base update check: Rufus_win_x64_6.3.ver
Trying Rufus_win_x64_6.3.ver
Detected Isolinux version: 3.86 (from '/isolinux.bin')
ISO label: ESXI-6.0.0-2494585-STANDARD
  Size: 365021184 bytes
  Has a >64 chars filename: No
  Has Symlinks: No
  Has a >4GB file: No
  Uses Bootmgr: No
  Uses EFI: Yes
  Uses Grub 2: No
  Uses Grub4DOS: No
  Uses isolinux: Yes (3.86)
    With an old menu.c32: Yes
    With an old vesamenu.c32: No
  Uses KolibriOS: No
  Uses ReactOS: No
  Uses WinPE: No
Using image: VMware-VMvisor-Installer-6.0.0-2494585.x86_64.iso
Trying Rufus_win_x64_6.ver
Trying Rufus_win_x64.ver
Trying Rufus_win.ver
Found match for Rufus_win.ver on server http://rufus.akeo.ie/
Server time: 13074300996
Successfully downloaded version file (1060 bytes)
UPDATE DATA:
  version: 2.1.649 (release)
  platform_min: 5.1
  url: http://rufus.akeo.ie/downloads/rufus-2.1.exe
No new release version found.
Checking beta channel...
Base update check: Rufus_beta_win_x64_6.3.ver
Trying Rufus_beta_win_x64_6.3.ver
Trying Rufus_beta_win_x64_6.ver
Trying Rufus_beta_win_x64.ver
Trying Rufus_beta_win.ver
Found match for Rufus_beta_win.ver on server http://rufus.akeo.ie/
Server time: 13074300997
Successfully downloaded version file (1212 bytes)
UPDATE DATA:
  version: 2.1.647 (beta)
  platform_min: 5.1
  url: http://rufus.akeo.ie/downloads/rufus-2.1_BETA.exe
No new beta version found.
Downloading 'menu.c32' from http://rufus.akeo.ie/files/syslinux-4.07/menu.c32
File length: 55140 bytes
Successfully downloaded 'menu.c32'

Format operation started
Requesting disk access...
Opened drive \\.\PHYSICALDRIVE5 for write access
Will use 'F:' as volume mountpoint
I/O boundary checks disabled
Analyzing existing boot records...
Drive has a Rufus Master Boot Record
Volume has an unknown Partition Boot Record
Deleting partitions...
Clearing MBR/PBR/GPT structures...
Erasing 2176 sectors
Partitioning (MBR)...
Closing existing volume...
Waiting for logical drive to reappear...
Closed Windows format prompt
Formatting (Large FAT32)...
Opened drive \\?\Volume{1b8f46a0-ea05-11e4-83fb-001fd0ad2d66} for write access
Size : 111.8 GB 234439600 sectors
Cluster size 32768 bytes, 512 Bytes Per Sector
Volume ID is 1eef:3020
32 Reserved Sectors, 28612 Sectors per FAT, 2 FATs
3662224 Total clusters
3662223 Free Clusters
Clearing out 57320 sectors for reserved sectors, FATs and root cluster...
Initializing reserved sectors and FATs...
FAT #0 sector at address: 32
FAT #1 sector at address: 28644
Writing partition boot record...
Using Standard FAT32 partition boot record
Confirmed new volume has a primary FAT32 boot sector
Setting primary FAT32 boot sector for boot...
Confirmed new volume has a secondary FAT32 boot sector
Setting secondary FAT32 boot sector for boot...
Setting Label (This may take while)...
Format completed.
Writing master boot record...
Drive has a Zeroed Master Boot Record
Partition is already FAT32 LBA...
Set bootable USB partition as 0x80
Using Syslinux MBR
Found volume GUID \\?\Volume{1b8f46a0-ea05-11e4-83fb-001fd0ad2d66}\
\\?\Volume{1b8f46a0-ea05-11e4-83fb-001fd0ad2d66}\ was already mounted as F:\
Installing Syslinux 3.86...
Successfully wrote 'ldlinux.sys'
Opened drive \\?\Volume{1b8f46a0-ea05-11e4-83fb-001fd0ad2d66} for write access
Successfully wrote Syslinux boot record
Successfully remounted Volume{1b8f46a0-ea05-11e4-83fb-001fd0ad2d66}\ on F:\
Copying ISO files...
Extracting files...
Disc image is an ISO9660 image
This image will be extracted using Joliet extensions (if present)
Extracting: F:\.discinfo (32 bytes)
Extracting: F:\a.b00 (11.0 KB)
Extracting: F:\ata_pata.v00 (8.3 KB)
Extracting: F:\ata_pata.v01 (6.2 KB)
Extracting: F:\ata_pata.v02 (6.5 KB)
Extracting: F:\ata_pata.v03 (7.2 KB)
Extracting: F:\ata_pata.v04 (8.3 KB)
Extracting: F:\ata_pata.v05 (7 KB)
Extracting: F:\ata_pata.v06 (6.2 KB)
Extracting: F:\ata_pata.v07 (7.6 KB)
Extracting: F:\b.b00 (74.4 KB)
Extracting: F:\block_cc.v00 (23.8 KB)
Extracting: F:\boot.cat (512 bytes)
Extracting: F:\boot.cfg (1.6 KB)
Extracting: F:\chardevs.b00 (18.6 KB)
Extracting: F:\efi\boot\boot.cfg (1.6 KB)
Extracting: F:\efi\boot\bootia32.efi (94.2 KB)
Extracting: F:\efi\boot\bootx64.efi (96.3 KB)
Extracting: F:\efiboot.img (1 MB)
Extracting: F:\ehci_ehc.v00 (33.3 KB)
Extracting: F:\elxnet.v00 (118 KB)
Extracting: F:\emulex_e.v00 (5.7 KB)
Extracting: F:\esx_dvfi.v00 (89.2 KB)
Extracting: F:\ima_qla4.v00 (359.4 KB)
Extracting: F:\imgdb.tgz (40.4 KB)
Extracting: F:\imgpayld.tgz (3.9 MB)
Extracting: F:\ipmi_ipm.v00 (9.4 KB)
Extracting: F:\ipmi_ipm.v01 (23.0 KB)
Extracting: F:\ipmi_ipm.v02 (27.9 KB)
Extracting: F:\isolinux.bin (14 KB)
Extracting: F:\isolinux.cfg (267 bytes)
Extracting: F:\jumpstrt.gz (20 bytes)
Extracting: F:\k.b00 (3.2 MB)
Extracting: F:\lpfc.v00 (492.5 KB)
Extracting: F:\lsi_mr3.v00 (68.8 KB)
Extracting: F:\lsi_msgp.v00 (118.0 KB)
Extracting: F:\lsu_hp_h.v00 (15.3 KB)
Extracting: F:\lsu_lsi_.v00 (78 KB)
Extracting: F:\lsu_lsi_.v01 (159.8 KB)
Extracting: F:\lsu_lsi_.v02 (74.8 KB)
Extracting: F:\lsu_lsi_.v03 (182.2 KB)
Extracting: F:\lsu_lsi_.v04 (114.3 KB)
Extracting: F:\mboot.c32 (83.9 KB)
Extracting: F:\menu.c32 (52.2 KB)
  Replaced with local version
Extracting: F:\misc_cni.v00 (5.5 KB)
Extracting: F:\misc_dri.v00 (1.2 MB)
Extracting: F:\mtip32xx.v00 (67.8 KB)
Extracting: F:\net_bnx2.v00 (167.8 KB)
Extracting: F:\net_bnx2.v01 (985.7 KB)
Extracting: F:\net_cnic.v00 (47.7 KB)
Extracting: F:\net_e100.v00 (93.7 KB)
Extracting: F:\net_e100.v01 (105.2 KB)
Extracting: F:\net_enic.v00 (43.6 KB)
Extracting: F:\net_forc.v00 (36.6 KB)
Extracting: F:\net_igb.v00 (103.8 KB)
Extracting: F:\net_ixgb.v00 (134.7 KB)
Extracting: F:\net_mlx4.v00 (107.8 KB)
Extracting: F:\net_mlx4.v01 (66.3 KB)
Extracting: F:\net_nx_n.v00 (1.3 MB)
Extracting: F:\net_tg3.v00 (108.7 KB)
Extracting: F:\net_vmxn.v00 (30.6 KB)
Extracting: F:\nmlx4_co.v00 (116.1 KB)
Extracting: F:\nmlx4_en.v00 (86.5 KB)
Extracting: F:\nmlx4_rd.v00 (39.9 KB)
Extracting: F:\nvme.v00 (49 KB)
Extracting: F:\ohci_usb.v00 (19.4 KB)
Extracting: F:\qlnative.v00 (684 KB)
Extracting: F:\rste.v00 (209.1 KB)
Extracting: F:\s.v00 (96.6 MB)
Extracting: F:\safeboot.c32 (61.7 KB)
Extracting: F:\sata_ahc.v00 (19.6 KB)
Extracting: F:\sata_ata.v00 (11.8 KB)
Extracting: F:\sata_sat.v00 (17.2 KB)
Extracting: F:\sata_sat.v01 (10.3 KB)
Extracting: F:\sata_sat.v02 (10.9 KB)
Extracting: F:\sata_sat.v03 (8 KB)
Extracting: F:\sata_sat.v04 (6.3 KB)
Extracting: F:\sb.v00 (48.1 MB)
Extracting: F:\scsi_aac.v00 (52.1 KB)
Extracting: F:\scsi_adp.v00 (143.3 KB)
Extracting: F:\scsi_aic.v00 (95.7 KB)
Extracting: F:\scsi_bnx.v00 (76.5 KB)
Extracting: F:\scsi_bnx.v01 (62 KB)
Extracting: F:\scsi_fni.v00 (64.1 KB)
Extracting: F:\scsi_hps.v00 (48.9 KB)
Extracting: F:\scsi_ips.v00 (32.1 KB)
Extracting: F:\scsi_meg.v00 (28.3 KB)
Extracting: F:\scsi_meg.v01 (54.1 KB)
Extracting: F:\scsi_meg.v02 (26.4 KB)
Extracting: F:\scsi_mpt.v00 (129.2 KB)
Extracting: F:\scsi_mpt.v01 (147.3 KB)
Extracting: F:\scsi_mpt.v02 (124.5 KB)
Extracting: F:\scsi_qla.v00 (74.8 KB)
Extracting: F:\tboot.b00 (43.3 KB)
Extracting: F:\tools.t00 (178.9 MB)
Extracting: F:\uc_amd.b00 (3.4 KB)
Extracting: F:\uc_intel.b00 (135.8 KB)
Extracting: F:\uhci_usb.v00 (19.8 KB)
Extracting: F:\upgrade\esximage.zip (865.5 KB)
Extracting: F:\upgrade\extlinux (62.5 KB)
Extracting: F:\upgrade\isoinfo (233.6 KB)
Extracting: F:\upgrade\mbr.bin (440 bytes)
Extracting: F:\upgrade\mcopy (584.2 KB)
Extracting: F:\upgrade\metadata.xml (1.5 KB)
Extracting: F:\upgrade\metadata.zip (94.2 KB)
Extracting: F:\upgrade\precheck.py (72.5 KB)
Extracting: F:\upgrade\prep.py (47.5 KB)
Extracting: F:\upgrade\profile.xml (7.1 KB)
Extracting: F:\user.b00 (439.9 KB)
Extracting: F:\useropts.gz (20 bytes)
Extracting: F:\vmware-esx-base-osl.txt (1.1 MB)
Extracting: F:\vmware-esx-base-readme (2.2 KB)
Extracting: F:\weaselin.t00 (1.9 MB)
Extracting: F:\xhci_xhc.v00 (57.1 KB)
Extracting: F:\xorg.v00 (1.3 MB)
Created: F:\syslinux.cfg
Finalizing, please wait...
Created: F:autorun.inf
Created: F:autorun.ico

Found UAS (USB 3.0) device 'Mushkin Ventura Ultra SCSI Disk Device' (174C:55AA)
Using autorun.inf label for drive F: 'ESXI-6.0.0-2494585-STANDARD'
1 device found
Disk type: Fixed, Sector Size: 512 bytes
Cylinders: 14593, TracksPerCylinder: 255, SectorsPerTrack: 63
Partition type: MBR, NB Partitions: 1
Disk ID: 0x00089D81
Drive has a Syslinux Master Boot Record
Partition 1:
  Type: FAT32 LBA (0x0c)
  Size: 111.8 GB (120033075200 bytes)
  Start Sector: 2048, Boot: Yes, Recognized: Yes
```

The issue is with your hardware...

**Comment by Dmanisaround** [comment] 2015-04-23 22:28
I'm using a microsoft surface pro connecting the usb drive directly to the usb 3.0 port. No hubs no cables no "subpar" hardware.

**Comment by pbatard** [comment] 2015-04-23 22:34
Then it's a SP incompatibility. As I explained, I see no issue whatsoever on my side, and I know a few other people have been able to use Rufus 2.x to install `VMware-VMvisor-Installer-6.0.0-2494585.x86_64.iso` on various USB devices.

Short of confirming that __ALL__ SP are affected, and someone sending me an SP to test, there's really nothing I can do.

**Comment by pbatard** [comment] 2015-04-27 00:59
Since there's nothing more I can do on this issue, I'm going to close it.

**Closed by pbatard** 2015-04-27 00:59 UTC

**Comment by ypupo2002** [comment] 2015-05-08 03:20
I have exactly this problem creating a Windows 8.1 bootable usb.

I'm using the same flash memory (Adata uv128 16GB usb3). Already tried two different memory sticks, on several machines (both sticks are brand new). The error occurs using both usb2 & usb3 ports, directly connected to the motherboard. It seems to be a problem with this specific brand and model.

**Comment by deepakshrma** [comment] 2016-12-18 14:06
1. Open Command Prompt, run as administrator mode
2. Open Rufus.exe

worked fine for me
