### ISSUE TITLE
Process accessing drive -> Can't mount GUID volume

### ISSUE THREAD

**Issue by C4V13R** [pbatard/rufus#1365] opened 2019-08-23 11:37 UTC
﻿

Checklist
---------
- [x] I looked at https://github.com/pbatard/rufus/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.
- [x] I clicked the 'Log' button or pressed <kbd>Ctrl</kbd>-<kbd>L</kbd> in Rufus, and copy/pasted the log into the line that says `<FULL LOG>` below.
- [x] The log I am copying is the FULL log, starting with the line `Rufus version: x.y.z` - I have NOT removed any part of it.

Additionally (if applicable):
- [ ] I ran a bad blocks check, by clicking _Show advanced format options_ then _Check device for bad blocks_, and confirmed that my USB is not defective.
- [ ] I also tried one or more of the following:
  - [ ] Using a different USB drive.
  - [ ] Plugging the USB into a different port.
  - [ ] Running Rufus on a different computer.
- [ ] If using an image, I clicked on the `(✓)` button to compute the MD5, SHA1 and SHA256 checksums, which are therefore present in the log I copied. I confirmed, by performing an internet search, that these values match the ones from the official image.

Issue description
-----------------
After setting Rufus up to perform a Windows 2 Go-installation, it first tells me before initiating the writing process that "processes are accessing my disk". I click something similar to "yes" to irregardless continue writing process. Then after formatting and starting the writing process, it fails due to "explorer.exe /r" accessing the disk still. After I kill the process in Windows Task Manager and restarting Rufus'  writing process all over again, it fails with a different error stating it "can't mount the GUID volume". I checked out a lot of posts considering the same error but nothing seems to fix the error I'm having.

Log
---
```
Rufus x86 v3.6.1551 (Portable)
Windows version: Windows 10 64-bit (Build 18362)
Syslinux versions: 4.07/2013-07-25, 6.03/2014-10-06
Grub versions: 0.4.6a, 2.04
System locale ID: 0x0413 (nl-NL)
NOTE: No Windows Language Pack is installed for English (English) on this system.
This means that some controls may still be displayed using the system locale.
SetLGP: Successfully set NoDriveTypeAutorun policy to 0x0000009E
Localization set to 'en-US'
Found UAS (USB 3.0) device 'Corsair Voyager GTX SCSI Disk Device' (1B1C:1A0E)
1 device found
Disk type: FIXED, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15566, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {21BA895C-4C91-420D-99A1-BE2D5B199608}
Max parts: 128, Start Offset: 17408, Usable = 128035641856 bytes
Partition 1:
  Type: {C12A7328-F81F-11D2-BA4B-00A0C93EC93B}
  Name: 'EFI System Partition'
  ID: {CEE074E3-853A-4BE2-A0EF-7530B37743FE}
  Size: 300 MB (314592768 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: {E3C9E316-0B5C-4DB8-817D-F92DF00215AE}
  Name: 'Microsoft Reserved Partition'
  ID: {732BA6FB-28C7-4592-8249-0B28F4FAD092}
  Size: 128 MB (134217728 bytes)
  Start Sector: 616487, Attributes: 0x0000000000000000
Partition 3:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Main Data Partition'
  ID: {8143C5CD-8955-4410-BA56-F5EA58EAC52E}
  Size: 118.8 GB (127585800192 bytes)
  Start Sector: 878631, Attributes: 0x0000000000000000
Found UAS (USB 3.0) device 'Corsair Voyager GTX SCSI Disk Device' (1B1C:1A0E)
1 device found
Disk type: FIXED, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15566, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {21BA895C-4C91-420D-99A1-BE2D5B199608}
Max parts: 128, Start Offset: 17408, Usable = 128035641856 bytes
Partition 1:
  Type: {C12A7328-F81F-11D2-BA4B-00A0C93EC93B}
  Name: 'EFI System Partition'
  ID: {CEE074E3-853A-4BE2-A0EF-7530B37743FE}
  Size: 300 MB (314592768 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: {E3C9E316-0B5C-4DB8-817D-F92DF00215AE}
  Name: 'Microsoft Reserved Partition'
  ID: {732BA6FB-28C7-4592-8249-0B28F4FAD092}
  Size: 128 MB (134217728 bytes)
  Start Sector: 616487, Attributes: 0x0000000000000000
Partition 3:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Main Data Partition'
  ID: {8143C5CD-8955-4410-BA56-F5EA58EAC52E}
  Size: 118.8 GB (127585800192 bytes)
  Start Sector: 878631, Attributes: 0x0000000000000000
Scanning image...
ISO analysis:
  Image is an UDF image
Disk image analysis:
  Image does not have an x86 Master Boot Record
ISO label: 'CCCOMA_X64FRE_EN-US_DV9'
  Size: 4.6 GB (Projected)
  Uses: EFI
  Uses: Bootmgr (BIOS and UEFI)
  Uses: Install.wim (version 0.13.1)
Using image: Win10_1903_V1_English_x64.iso (4.6 GB)
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Opening: \\.\CDROM0/sources/install.wim:[0] (API)
Extracting: C:\Users\Cas\AppData\Local\Temp\Ruf1889.tmp (From [1].xml)
Closing: \\.\CDROM0/sources/install.wim
Will use 'Windows 10 Home' (Build: 18362, Index 1) for Windows To Go

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 300 MB)
● Partition 2 (offset: 315641344, size: 128 MB)
● Partition 3 (offset: 449859072, size: 118.8 GB)
Opened \\.\PhysicalDrive2 for exclusive write access
No logical drive found (unpartitioned?)
Drive does not appear to be partitioned
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (GPT)...
● Creating EFI System Partition Partition (offset: 1048576, size: 300 MB)
● Creating Microsoft Reserved Partition Partition (offset: 315641344, size: 128 MB)
● Creating Main Data Partition (offset: 449859072, size: 118.8 GB)
Waiting for logical drive to reappear...
Closed Windows format prompt
Timeout while waiting for logical drive
Logical drive was not found!
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Using Rufus protective MBR
Found volume \\?\GLOBALROOT\Device\HarddiskVolume20\
Could not remount \\?\GLOBALROOT\Device\HarddiskVolume20\ as D: [0x00000012] Er zijn geen bestanden meer.
\\?\Volume{78458a4d-9e45-40b3-ac1c-7dfecfe42151}\ is already mounted as D:
Re-mounted volume as D: after error

Found UAS (USB 3.0) device 'Corsair Voyager GTX SCSI Disk Device' (1B1C:1A0E)
1 device found
Disk type: FIXED, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15566, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {BEE47081-E23F-487F-B285-BB61380135DC}
Max parts: 128, Start Offset: 17408, Usable = 128035641856 bytes
Partition 1:
  Type: {C12A7328-F81F-11D2-BA4B-00A0C93EC93B}
  Name: 'EFI System Partition'
  ID: {89616E3B-8339-47C0-A084-41F2ADB91F5C}
  Size: 300 MB (314592768 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: {E3C9E316-0B5C-4DB8-817D-F92DF00215AE}
  Name: 'Microsoft Reserved Partition'
  ID: {1C240A60-60FF-4F1B-9CB3-AD49A8EB635B}
  Size: 128 MB (134217728 bytes)
  Start Sector: 616487, Attributes: 0x0000000000000000
Partition 3:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Main Data Partition'
  ID: {78458A4D-9E45-40B3-AC1C-7DFECFE42151}
  Size: 118.8 GB (127585800192 bytes)
  Start Sector: 878631, Attributes: 0x0000000000000000
WIM extraction method(s) supported: 7-Zip, wimgapi.dll
WIM apply method supported: wimgapi.dll
Opening: \\.\CDROM0/sources/install.wim:[0] (API)
Extracting: C:\Users\Cas\AppData\Local\Temp\RufB92F.tmp (From [1].xml)
Closing: \\.\CDROM0/sources/install.wim
Will use 'Windows 10 Home' (Build: 18362, Index 1) for Windows To Go

Format operation started
Requesting disk access...
Will use 'D:' as volume mountpoint
Deleting partitions...
Deleting ALL partition(s) from disk '\\?\PhysicalDrive2':
● Partition 1 (offset: 1048576, size: 300 MB)
● Partition 2 (offset: 315641344, size: 128 MB)
● Partition 3 (offset: 449859072, size: 118.8 GB)
Opened \\.\PhysicalDrive2 for exclusive write access
No logical drive found (unpartitioned?)
Drive does not appear to be partitioned
Analyzing existing boot records...
Drive has a Zeroed Master Boot Record
Clearing MBR/PBR/GPT structures...
Erasing 128 sectors
Deleting partitions...
Partitioning (GPT)...
● Creating EFI System Partition Partition (offset: 1048576, size: 300 MB)
● Creating Microsoft Reserved Partition Partition (offset: 315641344, size: 128 MB)
● Creating Main Data Partition (offset: 449859072, size: 118.8 GB)
Waiting for logical drive to reappear...
Timeout while waiting for logical drive
Logical drive was not found!
Formatting (NTFS)...
Using cluster size: 4096 bytes
Quick format was selected
Creating file system...
Format completed.
Writing Master Boot Record...
Using Rufus protective MBR
Found volume \\?\GLOBALROOT\Device\HarddiskVolume23\
Could not remount \\?\GLOBALROOT\Device\HarddiskVolume23\ as D: [0x00000012] Er zijn geen bestanden meer.
\\?\Volume{61448bf4-6a1f-4132-a4e2-bfac37f9e2da}\ is already mounted as D:
Re-mounted volume as D: after error

Found UAS (USB 3.0) device 'Corsair Voyager GTX SCSI Disk Device' (1B1C:1A0E)
1 device found
Disk type: FIXED, Disk size: 128 GB, Sector size: 512 bytes
Cylinders: 15566, Tracks per cylinder: 255, Sectors per track: 63
Partition type: GPT, NB Partitions: 3
Disk GUID: {6F0F640F-99AE-45D1-8622-E38634C4894F}
Max parts: 128, Start Offset: 17408, Usable = 128035641856 bytes
Partition 1:
  Type: {C12A7328-F81F-11D2-BA4B-00A0C93EC93B}
  Name: 'EFI System Partition'
  ID: {2463BC40-9FC5-441B-8D70-EF937917D708}
  Size: 300 MB (314592768 bytes)
  Start Sector: 2048, Attributes: 0x0000000000000000
Partition 2:
  Type: {E3C9E316-0B5C-4DB8-817D-F92DF00215AE}
  Name: 'Microsoft Reserved Partition'
  ID: {60E37CE5-6899-4151-9701-EF2880232E39}
  Size: 128 MB (134217728 bytes)
  Start Sector: 616487, Attributes: 0x0000000000000000
Partition 3:
  Type: {EBD0A0A2-B9E5-4433-87C0-68B6B72699C7}
  Name: 'Main Data Partition'
  ID: {61448BF4-6A1F-4132-A4E2-BFAC37F9E2DA}
  Size: 118.8 GB (127585800192 bytes)
  Start Sector: 878631, Attributes: 0x0000000000000000

```

**Comment by pbatard** [comment] 2019-08-23 11:39
Duplicate of #1351. It will be fixed in the next release.

**Closed by pbatard** 2019-08-23 11:39 UTC
