### ISSUE TITLE
ISO selection should be First thing to select

### ISSUE THREAD

**Issue by mehargags** [pbatard/rufus#768] opened 2016-06-01 17:46 UTC
I've been using Rufus past so many years and always face problem because first we are given choice of Selecting the GPT/MBR scheme, no matter what you choose, it is reset when you select the ISO from the dialog box.

Either please fix it NOT to reset the MBR/GPT selection made before or re-locate the ISO Selection prior to GPT/MBR Selection.

You only realize that after wasting 15 mins that it is not a GPT disk, the ISO selection reset it to MBR one.

**Comment by pbatard** [comment] 2016-06-01 20:10
Duplicate of #117.

**Closed by pbatard** 2016-06-01 20:10 UTC
